// ═══ DATA ═══
const SP=['https://i.pravatar.cc/300?img=12','https://i.pravatar.cc/300?img=5','https://i.pravatar.cc/300?img=11','https://i.pravatar.cc/300?img=9','https://i.pravatar.cc/300?img=14','https://i.pravatar.cc/300?img=16','https://i.pravatar.cc/300?img=33','https://i.pravatar.cc/300?img=32','https://i.pravatar.cc/300?img=51','https://i.pravatar.cc/300?img=44','https://i.pravatar.cc/300?img=53','https://i.pravatar.cc/300?img=31','https://i.pravatar.cc/300?img=60','https://i.pravatar.cc/300?img=61','https://i.pravatar.cc/300?img=62','https://i.pravatar.cc/300?img=63'];
let chars=[
  {id:'c1',n:'Acun',s:'Dönmez',rep:'',a:true,img:'/images/acun-donmez.jpg',tip:'Lider',g:'M'},
  {id:'c2',n:'Adem',s:'Baltacı',rep:'',a:true,img:'/images/adem-baltaci.jpg',tip:'Yalancı',g:'M'},
  {id:'c3',n:'Adrian',s:'Ashford',rep:'',a:true,img:'/images/adrian-ashford.jpg',tip:'Dedikoducu',g:'M'},
  {id:'c4',n:'Aera',s:'Hwang',rep:'',a:true,img:'/images/aera-hwang.jpg',tip:'Korkak',g:'F'},
  {id:'c5',n:'Akira',s:'Nishida',rep:'',a:true,img:'/images/akira-nishida.jpg',tip:'Cesur',g:'M'},
  {id:'c6',n:'Akın',s:'Bagatur',rep:'',a:true,img:'/images/akin-bagatur.jpg',tip:'Aptal',g:'M'},
  {id:'c7',n:'Ala',s:'Lydia Lynn Alcazar',rep:'',a:true,img:'/images/ala-lydia-lynn.jpg',tip:'Kavgacı',g:'F'},
  {id:'c8',n:'Aleksey',s:'Marvin',rep:'',a:true,img:'',tip:'Araba Delisi',g:'M'},
  {id:'c9',n:'Alessia',s:'Hill',rep:'',a:true,img:'/images/alessia-hill.jpg',tip:'Silah Delisi',g:'F'},
  {id:'c10',n:'Alexander',s:'Cruz',rep:'',a:true,img:'',tip:'Sadık',g:'M'},
  {id:'c11',n:'Alfonzo',s:'Williams',rep:'',a:true,img:'/images/alfonzo-williams.jpg',tip:'Hain',g:'M'},
  {id:'c12',n:'Alfredo',s:'Sebastian',rep:'',a:true,img:'',tip:'Cimri',g:'M'},
  {id:'c13',n:'Ali',s:'Gözebatan',rep:'',a:true,img:'/images/ali-gozebatan.jpg',tip:'Hovarda',g:'M'},
  {id:'c14',n:'Alice',s:'Cornelia Rhodes',rep:'',a:true,img:'/images/alice-miu-moon.jpg',tip:'Soğukkanlı',g:'F'},
  {id:'c15',n:'Alice',s:'Miu Moon',rep:'',a:true,img:'/images/alice-miu-moon.jpg',tip:'Sinirli',g:'F'},
  {id:'c16',n:'Alpay',s:'Omarov',rep:'',a:true,img:'',tip:'Tembel',g:'M'},
  {id:'c17',n:'Alper',s:'Mermer',rep:'',a:true,img:'/images/alper-mermer.jpg',tip:'Çalışkan',g:'M'},
  {id:'c18',n:'Alperen',s:'Konan',rep:'',a:true,img:'/images/alperen-konan.jpg',tip:'Romantik',g:'M'},
  {id:'c19',n:'Amethyst',s:'Bellmore',rep:'',a:true,img:'/images/amethyst-bellmore.jpg',tip:'Kıskanç',g:'F'},
  {id:'c20',n:'Amy',s:'Hermann',rep:'',a:true,img:'/images/amy-hermann.jpg',tip:'Şüpheci',g:'F'},
  {id:'c21',n:'Ana',s:'Vitória Ramos',rep:'',a:true,img:'',tip:'Maceracı',g:'F'},
  {id:'c22',n:'André',s:'Claude',rep:'',a:true,img:'',tip:'Karizmatik',g:'M'},
  {id:'c23',n:'Andy',s:'Deer',rep:'',a:true,img:'/images/andy-deer.jpg',tip:'Manipülatif',g:'M'},
  {id:'c24',n:'Arat',s:'Soykan',rep:'',a:true,img:'/images/necla-karatas.jpg',tip:'Fedakar',g:'M'},
  {id:'c25',n:'Aras',s:'Ateş',rep:'',a:true,img:'',tip:'Bencil',g:'M'},
  {id:'c26',n:'Arman',s:'Aksu',rep:'',a:true,img:'/images/arman-aksu.jpg',tip:'Asi',g:'M'},
  {id:'c27',n:'Artuç',s:'Kılıç',rep:'',a:true,img:'/images/artuc-kilic.jpg',tip:'Paracı',g:'M'},
  {id:'c28',n:'Arya',s:'Demir',rep:'',a:true,img:'',tip:'Hesapçı',g:'F'},
  {id:'c29',n:'Ateş',s:'Akın',rep:'',a:true,img:'/images/kuzey-ates.jpg',tip:'Vicdanlı',g:'M'},
  {id:'c30',n:'Ateş',s:'Kuzgun',rep:'',a:true,img:'/images/ates-kuzgun.jpg',tip:'Psikopat',g:'M'},
  {id:'c31',n:'Atilla',s:'Tekin',rep:'',a:true,img:'/images/atilla-tekin.jpg',tip:'Lider',g:'M'},
  {id:'c32',n:'Barbaros',s:'Kalender',rep:'',a:true,img:'',tip:'Yalancı',g:'M'},
  {id:'c33',n:'Baybars',s:'Kurt',rep:'',a:true,img:'/images/baybars-kurt.jpg',tip:'Dedikoducu',g:'M'},
  {id:'c34',n:'Bayezid',s:'Bolatlı',rep:'',a:true,img:'',tip:'Korkak',g:'M'},
  {id:'c35',n:'Benjamin',s:'Clark',rep:'',a:true,img:'',tip:'Cesur',g:'M'},
  {id:'c36',n:'Berkan',s:'Kaburgedik',rep:'',a:true,img:'/images/berkan-kaburgedik.jpg',tip:'Aptal',g:'M'},
  {id:'c37',n:'Berkay',s:'Yazıcı',rep:'',a:true,img:'/images/berkay-yazici.jpg',tip:'Kavgacı',g:'M'},
  {id:'c38',n:'Berken',s:'Aslanoğlu',rep:'',a:true,img:'/images/berken-aslanoglu.jpg',tip:'Araba Delisi',g:'M'},
  {id:'c39',n:'Bethany',s:'Marlowe',rep:'',a:true,img:'/images/bethany-marlowe.jpg',tip:'Silah Delisi',g:'F'},
  {id:'c40',n:'Bircan',s:'Koray',rep:'',a:true,img:'',tip:'Sadık',g:'M'},
  {id:'c41',n:'Blackrose',s:'',rep:'',a:true,img:'',tip:'Hain',g:'F'},
  {id:'c42',n:'Bluur',s:'',rep:'',a:true,img:'',tip:'Cimri',g:'M'},
  {id:'c43',n:'Burak',s:'Alparslan',rep:'',a:true,img:'/images/burak-alparslan.jpg',tip:'Hovarda',g:'M'},
  {id:'c44',n:'Burak',s:'Kara',rep:'',a:true,img:'/images/burak-kara.jpg',tip:'Soğukkanlı',g:'M'},
  {id:'c45',n:'Can',s:'Demir',rep:'',a:true,img:'',tip:'Sinirli',g:'M'},
  {id:'c46',n:'Can',s:'Kaya',rep:'',a:true,img:'',tip:'Tembel',g:'M'},
  {id:'c47',n:'Cansu',s:'Ünal',rep:'',a:true,img:'',tip:'Çalışkan',g:'F'},
  {id:'c48',n:'Carolyn',s:'Cross',rep:'',a:true,img:'',tip:'Romantik',g:'F'},
  {id:'c49',n:'Cem',s:'Demir',rep:'',a:true,img:'/images/cem-demir.jpg',tip:'Kıskanç',g:'M'},
  {id:'c50',n:'Cenk',s:'Özer',rep:'',a:true,img:'/images/cenk-ozer.jpg',tip:'Şüpheci',g:'M'},
  {id:'c51',n:'Chris',s:'Stanley',rep:'',a:true,img:'',tip:'Maceracı',g:'M'},
  {id:'c52',n:'Cordiseps',s:'',rep:'',a:true,img:'/images/cordiseps.jpg',tip:'Karizmatik',g:'M'},
  {id:'c53',n:'Craig',s:'Jones',rep:'',a:true,img:'',tip:'Manipülatif',g:'M'},
  {id:'c54',n:'Curtis',s:'Junko',rep:'',a:true,img:'/images/curtis-junko-cj.jpg',tip:'Fedakar',g:'M'},
  {id:'c55',n:'Damon',s:'Braus',rep:'',a:true,img:'',tip:'Bencil',g:'M'},
  {id:'c56',n:'Daniel',s:'Walker',rep:'',a:true,img:'',tip:'Asi',g:'M'},
  {id:'c57',n:'Daryl',s:'Mayer',rep:'',a:true,img:'/images/daryl-mayer.jpg',tip:'Paracı',g:'M'},
  {id:'c58',n:'Davi',s:'Lucas Martins',rep:'',a:true,img:'/images/davi-lucas-martins.jpg',tip:'Hesapçı',g:'M'},
  {id:'c59',n:'Davut',s:'Tokgöz',rep:'',a:true,img:'/images/davut-tokgoz.jpg',tip:'Vicdanlı',g:'M'},
  {id:'c60',n:'Dean',s:'Callahan',rep:'',a:true,img:'',tip:'Psikopat',g:'M'},
  {id:'c61',n:'Dean',s:'Cliff',rep:'',a:true,img:'',tip:'Lider',g:'M'},
  {id:'c62',n:'Deniz',s:'Tetik',rep:'',a:true,img:'',tip:'Yalancı',g:'M'},
  {id:'c63',n:'Dimitri',s:'Ivanov',rep:'',a:true,img:'/images/dimitri-ivanov.jpg',tip:'Dedikoducu',g:'M'},
  {id:'c64',n:'Distopya',s:'',rep:'',a:true,img:'',tip:'Korkak',g:'M'},
  {id:'c65',n:'Dominic',s:'Luck',rep:'',a:true,img:'/images/dominic-luck.jpg',tip:'Cesur',g:'M'},
  {id:'c66',n:'Doruk',s:'Aydın',rep:'',a:true,img:'',tip:'Aptal',g:'M'},
  {id:'c67',n:'Dragan',s:'Valchev',rep:'',a:true,img:'/images/dragan-valchev.jpg',tip:'Kavgacı',g:'M'},
  {id:'c68',n:'Drake',s:'LeRoi',rep:'',a:true,img:'/images/drake-leroi.jpg',tip:'Araba Delisi',g:'M'},
  {id:'c69',n:'Duncan',s:'Johnson',rep:'',a:true,img:'/images/duncan-jevonte-johnson.jpg',tip:'Silah Delisi',g:'M'},
  {id:'c70',n:'Edwin',s:'Jorgensen',rep:'',a:true,img:'/images/edwin-jorgensen.jpg',tip:'Sadık',g:'M'},
  {id:'c71',n:'Egan',s:'Rak',rep:'',a:true,img:'',tip:'Hain',g:'M'},
  {id:'c72',n:'Elraen',s:'',rep:'',a:true,img:'',tip:'Cimri',g:'M'},
  {id:'c73',n:'Emine',s:'Şaşkın',rep:'',a:true,img:'/images/emine-saskin.jpg',tip:'Hovarda',g:'F'},
  {id:'c74',n:'Ender',s:'Akın',rep:'',a:true,img:'/images/ender-akin.jpg',tip:'Soğukkanlı',g:'M'},
  {id:'c75',n:'Enrico',s:'D\'alessandro',rep:'',a:true,img:'',tip:'Sinirli',g:'M'},
  {id:'c76',n:'Ercan',s:'Karabudak',rep:'',a:true,img:'',tip:'Tembel',g:'M'},
  {id:'c77',n:'Ethan',s:'Frost',rep:'',a:true,img:'/images/ethan-frost.jpg',tip:'Çalışkan',g:'M'},
  {id:'c78',n:'Evan',s:'Elain',rep:'',a:true,img:'/images/evan-elain.jpg',tip:'Romantik',g:'M'},
  {id:'c79',n:'Ezra',s:'Johnson',rep:'',a:true,img:'/images/ezra-johnson.jpg',tip:'Kıskanç',g:'M'},
  {id:'c80',n:'Fabien',s:'Fortune',rep:'',a:true,img:'',tip:'Şüpheci',g:'M'},
  {id:'c81',n:'Fatih',s:'Vatoz',rep:'',a:true,img:'',tip:'Maceracı',g:'M'},
  {id:'c82',n:'Ferit',s:'Bayraktar',rep:'',a:true,img:'/images/ferit-bayraktar.jpg',tip:'Karizmatik',g:'M'},
  {id:'c83',n:'Feyzullah',s:'Gözebatan',rep:'',a:true,img:'/images/feyzullah-gozebatan.jpg',tip:'Manipülatif',g:'M'},
  {id:'c84',n:'Fifi',s:'Bombisa',rep:'',a:true,img:'/images/fifi-bombisa.jpg',tip:'Fedakar',g:'F'},
  {id:'c85',n:'Finn',s:'Fisher',rep:'',a:true,img:'/images/finn-fisher.jpg',tip:'Bencil',g:'M'},
  {id:'c86',n:'Furkan',s:'Kaplan',rep:'',a:true,img:'/images/furkan-kaplan.jpg',tip:'Asi',g:'M'},
  {id:'c87',n:'Gale',s:'Godlock',rep:'',a:true,img:'/images/gale-godlock.jpg',tip:'Paracı',g:'M'},
  {id:'c88',n:'Geralt',s:'Warner',rep:'',a:true,img:'',tip:'Hesapçı',g:'M'},
  {id:'c89',n:'Grace',s:'Wyns',rep:'',a:true,img:'',tip:'Vicdanlı',g:'F'},
  {id:'c90',n:'Grayson',s:'Martinez',rep:'',a:true,img:'/images/grayson-martinez.jpg',tip:'Psikopat',g:'M'},
  {id:'c91',n:'Güneş',s:'Yazgın',rep:'',a:true,img:'/images/gunes-yazgin.jpg',tip:'Lider',g:'F'},
  {id:'c92',n:'Gustavo',s:'Lobo',rep:'',a:true,img:'',tip:'Yalancı',g:'M'},
  {id:'c93',n:'Halil',s:'Recai',rep:'',a:true,img:'',tip:'Dedikoducu',g:'M'},
  {id:'c94',n:'Hank',s:'Hornet',rep:'',a:true,img:'',tip:'Korkak',g:'M'},
  {id:'c95',n:'Harry',s:'Ambrose',rep:'',a:true,img:'/images/harry-ambrose.jpg',tip:'Cesur',g:'M'},
  {id:'c96',n:'Harvey',s:'Delon',rep:'',a:true,img:'/images/harvey-delon.jpg',tip:'Aptal',g:'M'},
  {id:'c97',n:'Héctor',s:'Montes',rep:'',a:true,img:'',tip:'Kavgacı',g:'M'},
  {id:'c98',n:'Henry',s:'Graves',rep:'',a:true,img:'',tip:'Araba Delisi',g:'M'},
  {id:'c99',n:'Icarus',s:'Dravemour',rep:'',a:true,img:'/images/icarus-sir-dravemour.jpg',tip:'Silah Delisi',g:'M'},
  {id:'c100',n:'İlker',s:'Çiftci',rep:'',a:true,img:'/images/ilker-ciftci.jpg',tip:'Sadık',g:'M'},
  {id:'c101',n:'Ilya',s:'Estovsky',rep:'',a:true,img:'',tip:'Hain',g:'M'},
  {id:'c102',n:'Isaac',s:'Kawashima',rep:'',a:true,img:'',tip:'Cimri',g:'M'},
  {id:'c103',n:'James',s:'Cart',rep:'',a:true,img:'',tip:'Hovarda',g:'M'},
  {id:'c104',n:'Jason',s:'Walker',rep:'',a:true,img:'',tip:'Soğukkanlı',g:'M'},
  {id:'c105',n:'Javier',s:'Delgado',rep:'',a:true,img:'',tip:'Sinirli',g:'M'},
  {id:'c106',n:'Jax',s:'Jane',rep:'',a:true,img:'/images/jax-jane.jpg',tip:'Tembel',g:'M'},
  {id:'c107',n:'Jaxon',s:'Palmer',rep:'',a:true,img:'/images/jaxon-palmer.jpg',tip:'Çalışkan',g:'M'},
  {id:'c108',n:'Jayden',s:'Crawford',rep:'',a:true,img:'/images/jayden-crawford.jpg',tip:'Romantik',g:'M'},
  {id:'c109',n:'Jeff',s:'Nikov',rep:'',a:true,img:'',tip:'Kıskanç',g:'M'},
  {id:'c110',n:'Jessica',s:'Şengöl',rep:'',a:true,img:'/images/jessica-sengol.jpg',tip:'Şüpheci',g:'F'},
  {id:'c111',n:'Johannes',s:'Corvus',rep:'',a:true,img:'/images/johannes-de-corvus.jpg',tip:'Maceracı',g:'M'},
  {id:'c112',n:'Jonathan',s:'Dream',rep:'',a:true,img:'/images/jonathan-dream.jpg',tip:'Karizmatik',g:'M'},
  {id:'c113',n:'Jules',s:'Weiß',rep:'',a:true,img:'',tip:'Manipülatif',g:'M'},
  {id:'c114',n:'Kadir',s:'Duman',rep:'',a:true,img:'/images/kadir-duman.jpg',tip:'Fedakar',g:'M'},
  {id:'c115',n:'Kane',s:'Wells',rep:'',a:true,img:'/images/kane-wells.jpg',tip:'Bencil',g:'M'},
  {id:'c116',n:'Kasey',s:'Wail',rep:'',a:true,img:'',tip:'Asi',g:'M'},
  {id:'c117',n:'Kemal',s:'Türkel',rep:'',a:true,img:'/images/kemal-mete-turkel.jpg',tip:'Paracı',g:'M'},
  {id:'c118',n:'Kerem',s:'Cengaver',rep:'',a:true,img:'',tip:'Hesapçı',g:'M'},
  {id:'c119',n:'Kerem',s:'Yılmaz',rep:'',a:true,img:'',tip:'Vicdanlı',g:'M'},
  {id:'c120',n:'Kevin',s:'Williams',rep:'',a:true,img:'/images/kevin-williams.jpg',tip:'Psikopat',g:'M'},
  {id:'c121',n:'Koray',s:'Miller',rep:'',a:true,img:'/images/koray-miller.jpg',tip:'Lider',g:'M'},
  {id:'c122',n:'Kubilay',s:'Yaşar',rep:'',a:true,img:'/images/kubilay-yasar.jpg',tip:'Yalancı',g:'M'},
  {id:'c123',n:'Kuzey',s:'Akıncı',rep:'',a:true,img:'/images/kuzey-akinci.jpg',tip:'Dedikoducu',g:'M'},
  {id:'c124',n:'Kuzey',s:'Ateş',rep:'',a:true,img:'/images/kuzey-ates.jpg',tip:'Korkak',g:'M'},
  {id:'c125',n:'Leon',s:'Wolf',rep:'',a:true,img:'',tip:'Cesur',g:'M'},
  {id:'c126',n:'Leroy',s:'Wilson',rep:'',a:true,img:'/images/leroy-wilson.jpg',tip:'Aptal',g:'M'},
  {id:'c127',n:'Levent',s:'Polat',rep:'',a:true,img:'',tip:'Kavgacı',g:'M'},
  {id:'c128',n:'Lion',s:'Claw',rep:'',a:true,img:'/images/lion-andrew.jpg',tip:'Araba Delisi',g:'M'},
  {id:'c129',n:'Liora',s:'Rosenfeld',rep:'',a:true,img:'/images/liora-rosenfeld.jpg',tip:'Silah Delisi',g:'F'},
  {id:'c130',n:'Luna',s:'Çkır',rep:'',a:true,img:'',tip:'Sadık',g:'F'},
  {id:'c131',n:'Logan',s:'Knox',rep:'',a:true,img:'/images/logan-knox.jpg',tip:'Hain',g:'M'},
  {id:'c132',n:'Logan',s:'Doyle',rep:'',a:true,img:'/images/logan-knox.jpg',tip:'Cimri',g:'M'},
  {id:'c133',n:'Loris',s:'Kane',rep:'',a:true,img:'',tip:'Hovarda',g:'M'},
  {id:'c134',n:'Lucas',s:'Carter',rep:'',a:true,img:'/images/davi-lucas-martins.jpg',tip:'Soğukkanlı',g:'M'},
  {id:'c135',n:'Luis',s:'Pareja',rep:'',a:true,img:'/images/luis-pareja.jpg',tip:'Sinirli',g:'M'},
  {id:'c136',n:'Maddy',s:'Westwood',rep:'',a:true,img:'/images/maddy-westwood.jpg',tip:'Tembel',g:'F'},
  {id:'c137',n:'Magnus',s:'Hargrove',rep:'',a:true,img:'/images/magnus-hargrove.jpg',tip:'Çalışkan',g:'M'},
  {id:'c138',n:'Marcello',s:'Baldiserra',rep:'',a:true,img:'',tip:'Romantik',g:'M'},
  {id:'c139',n:'Marcos',s:'Franco',rep:'',a:true,img:'/images/marcos-magalhaes-franco.jpg',tip:'Kıskanç',g:'M'},
  {id:'c140',n:'Marcus',s:'Newton',rep:'',a:true,img:'/images/marcus-newton.jpg',tip:'Şüpheci',g:'M'},
  {id:'c141',n:'Markus',s:'Guven',rep:'',a:true,img:'/images/markus-guven.jpg',tip:'Maceracı',g:'M'},
  {id:'c142',n:'Marquise',s:'Jay',rep:'',a:true,img:'',tip:'Karizmatik',g:'M'},
  {id:'c143',n:'Mason',s:'Doakes',rep:'',a:true,img:'',tip:'Manipülatif',g:'M'},
  {id:'c144',n:'Memduh',s:'Basmacı',rep:'',a:true,img:'/images/memduh-basmaci.jpg',tip:'Fedakar',g:'M'},
  {id:'c145',n:'Miguel',s:'Oliveira',rep:'',a:true,img:'',tip:'Bencil',g:'M'},
  {id:'c146',n:'Miku',s:'Kolgrim',rep:'',a:true,img:'/images/miku-misaki-kolgrim.jpg',tip:'Asi',g:'F'},
  {id:'c147',n:'Milean',s:'',rep:'',a:true,img:'',tip:'Paracı',g:'M'},
  {id:'c148',n:'Miles',s:'Ramirez',rep:'',a:true,img:'',tip:'Hesapçı',g:'M'},
  {id:'c149',n:'Modibo',s:'Junior',rep:'',a:true,img:'/images/modibo-junior.jpg',tip:'Vicdanlı',g:'M'},
  {id:'c150',n:'Murphy',s:'McConaughey',rep:'',a:true,img:'',tip:'Psikopat',g:'M'},
  {id:'c151',n:'Naia',s:'Xanthe',rep:'',a:true,img:'',tip:'Lider',g:'F'},
  {id:'c152',n:'Nart',s:'Kağan',rep:'',a:true,img:'',tip:'Yalancı',g:'M'},
  {id:'c153',n:'Necla',s:'Karataş',rep:'',a:true,img:'/images/necla-karatas.jpg',tip:'Dedikoducu',g:'F'},
  {id:'c154',n:'Nedim',s:'Hirschmeier',rep:'',a:true,img:'/images/nedim-stefan-hirschmeier.jpg',tip:'Korkak',g:'M'},
  {id:'c155',n:'Nefari',s:'Zavod',rep:'',a:true,img:'',tip:'Cesur',g:'F'},
  {id:'c156',n:'Nemesis',s:'',rep:'',a:true,img:'',tip:'Aptal',g:'M'},
  {id:'c157',n:'Neo',s:'Dexter',rep:'',a:true,img:'/images/neo-dexter.jpg',tip:'Kavgacı',g:'M'},
  {id:'c158',n:'Neşet',s:'Sümer',rep:'',a:true,img:'',tip:'Araba Delisi',g:'M'},
  {id:'c159',n:'Oliver',s:'Watkins',rep:'',a:true,img:'/images/oliver-watkins.jpg',tip:'Silah Delisi',g:'M'},
  {id:'c160',n:'Ophelia',s:'Edina',rep:'',a:true,img:'/images/ophelia-edina.jpg',tip:'Sadık',g:'F'},
  {id:'c161',n:'Orçun',s:'Avcı',rep:'',a:true,img:'',tip:'Hain',g:'M'},
  {id:'c162',n:'Owen',s:'Garcia',rep:'',a:true,img:'',tip:'Cimri',g:'M'},
  {id:'c163',n:'Rafet',s:'Atamer',rep:'',a:true,img:'',tip:'Hovarda',g:'M'},
  {id:'c164',n:'Randy',s:'Rathbone',rep:'',a:true,img:'',tip:'Soğukkanlı',g:'M'},
  {id:'c165',n:'Raphaël',s:'Garcia',rep:'',a:true,img:'',tip:'Sinirli',g:'M'},
  {id:'c166',n:'Reinn',s:'Alastair',rep:'',a:true,img:'',tip:'Tembel',g:'M'},
  {id:'c167',n:'Ren',s:'Shimada',rep:'',a:true,img:'/images/ren-shimada.jpg',tip:'Çalışkan',g:'M'},
  {id:'c168',n:'Rey',s:'Aragon',rep:'',a:true,img:'/images/rey-aragon.jpg',tip:'Romantik',g:'M'},
  {id:'c169',n:'Rico',s:'Cruz',rep:'',a:true,img:'',tip:'Kıskanç',g:'M'},
  {id:'c170',n:'Robert',s:'Finch',rep:'',a:true,img:'',tip:'Şüpheci',g:'M'},
  {id:'c171',n:'Rodrigo',s:'Hector',rep:'',a:true,img:'/images/rodrigo-hector.jpg',tip:'Maceracı',g:'M'},
  {id:'c172',n:'Roger',s:'Smith',rep:'',a:true,img:'',tip:'Karizmatik',g:'M'},
  {id:'c173',n:'Roman',s:'Blackwood',rep:'',a:true,img:'/images/roman-blackwood.jpg',tip:'Manipülatif',g:'M'},
  {id:'c174',n:'Rosalie',s:'Smith',rep:'',a:true,img:'/images/rosalie-smith.jpg',tip:'Fedakar',g:'F'},
  {id:'c175',n:'Samuel',s:'Orsic',rep:'',a:true,img:'/images/samuel-orsich.jpg',tip:'Bencil',g:'M'},
  {id:'c176',n:'Sarp',s:'Eser',rep:'',a:true,img:'/images/saitsarp.jpg',tip:'Asi',g:'M'},
  {id:'c177',n:'Savio',s:'D\'alessandro',rep:'',a:true,img:'/images/savio-dalessandro.jpg',tip:'Paracı',g:'M'},
  {id:'c178',n:'Sean',s:'Edwards',rep:'',a:true,img:'/images/sean-edwars.jpg',tip:'Hesapçı',g:'M'},
  {id:'c179',n:'Sendō',s:'Kyotaro',rep:'',a:true,img:'',tip:'Vicdanlı',g:'M'},
  {id:'c180',n:'Sophia',s:'Bennett',rep:'',a:true,img:'/images/sophia-bennett.jpg',tip:'Psikopat',g:'F'},
  {id:'c181',n:'Sungur',s:'Yılmaz',rep:'',a:true,img:'',tip:'Lider',g:'M'},
  {id:'c182',n:'Sylvester',s:'Coachella',rep:'',a:true,img:'/images/sylvester-coachella.jpg',tip:'Yalancı',g:'M'},
  {id:'c183',n:'Syna',s:'',rep:'',a:true,img:'',tip:'Dedikoducu',g:'F'},
  {id:'c184',n:'Talya',s:'Demir',rep:'',a:true,img:'/images/talya-demir.jpg',tip:'Korkak',g:'F'},
  {id:'c185',n:'Theo',s:'Mortimer',rep:'',a:true,img:'/images/theo-mortimer.jpg',tip:'Cesur',g:'M'},
  {id:'c186',n:'Theo',s:'Wells',rep:'',a:true,img:'/images/theo-wells.jpg',tip:'Aptal',g:'M'},
  {id:'c187',n:'Tolga',s:'Kaynakçı',rep:'',a:true,img:'',tip:'Kavgacı',g:'M'},
  {id:'c188',n:'Tony',s:'Carbone',rep:'',a:true,img:'/images/tony-carbone.jpg',tip:'Araba Delisi',g:'M'},
  {id:'c189',n:'Troy',s:'Colton',rep:'',a:true,img:'/images/troy-colton.jpg',tip:'Silah Delisi',g:'M'},
  {id:'c190',n:'Tuana',s:'Kaybetmez',rep:'',a:true,img:'/images/tuana-kaybetmez.jpg',tip:'Sadık',g:'F'},
  {id:'c191',n:'Valaska',s:'',rep:'',a:true,img:'',tip:'Hain',g:'F'},
  {id:'c192',n:'Valian',s:'Miller',rep:'',a:true,img:'/images/valian-miller.jpg',tip:'Cimri',g:'M'},
  {id:'c193',n:'Valto',s:'Martines',rep:'',a:true,img:'',tip:'Hovarda',g:'M'},
  {id:'c194',n:'Veronica',s:'Valenti',rep:'',a:true,img:'/images/veronica-valenti.jpg',tip:'Soğukkanlı',g:'F'},
  {id:'c195',n:'Vladimir',s:'Zavodsky',rep:'',a:true,img:'/images/vladimir-zavodsky.jpg',tip:'Sinirli',g:'M'},
  {id:'c196',n:'Wesley',s:'Marlowe',rep:'',a:true,img:'/images/wesley-harper.jpg',tip:'Tembel',g:'M'},
  {id:'c197',n:'William',s:'Clay',rep:'',a:true,img:'/images/kevin-williams.jpg',tip:'Çalışkan',g:'M'},
  {id:'c198',n:'Yekaterina',s:'Petrova',rep:'',a:true,img:'/images/yekaterina-petrova.jpg',tip:'Romantik',g:'F'},
  {id:'c199',n:'Zafer',s:'Gün',rep:'',a:true,img:'/images/zafer-gun.jpg',tip:'Kıskanç',g:'M'},
  {id:'c200',n:'Zeca',s:'Vance',rep:'',a:true,img:'',tip:'Şüpheci',g:'M'},
  {id:'c201',n:'Zale',s:'',rep:'',a:true,img:'',tip:'Maceracı',g:'M'}
];
// Users managed server-side — no credentials in frontend
let users=[];
let curUser=null;
let whoQs=[
  {id:'wq1',q:'Arkadaşın sana bir sır söyledi. Ne yaparsın?',o:['Mezara kadar saklarım','Bi kişiye söylerim sadece...','İleride lazım olur, not alırım','Umurumda olmaz']},
  {id:'wq2',q:'Sokakta bir kavga çıktı. İlk tepkin?',o:['Dalıyorum tabii','Sessizce uzaklaşırım','İzlerim, gerekirse müdahale ederim','Video çekerim']},
  {id:'wq3',q:'Birisi sana yalan söylediğini fark ettin.',o:['Zaten güvenmiyordum kimseye','Yüzüne söylerim hemen','Ben de daha büyük yalan söylerim','Umursamam, herkes yalan söyler']},
  {id:'wq4',q:'Rüyandaki araç hangisi?',o:['V8 motor, tam gaz!','En pahalısı hangisiyse','Beni götürsün yeter','Motor tercihimdir']},
  {id:'wq5',q:'Silah konusunda ne düşünürsün?',o:['Koleksiyon yapıyorum','Yakınında bile durmam','Gerekirse kullanırım','Şiddet çözüm değil']},
  {id:'wq6',q:'Patron senden fazla mesai istedi.',o:['Tamam, yaparım sorunsuz','Bahane uydurup kaçarım','Hakkım değilse yapmam','Karşılığında ne var?']},
  {id:'wq7',q:'Sevgilin başkasıyla konuşuyormuş.',o:['Deliye dönerim','Kalbim kırılır ama konuşurum','Ben de başkasını bulurum','Önce kanıt toplarım']},
  {id:'wq8',q:'Cebinde son 100 lira var.',o:['Biriktiririm','Arkadaşlara ısmarlarm','Yatırım yaparım','Şansımı denerim']},
  {id:'wq9',q:'Bir gruba yeni katıldın.',o:['Herkesle hemen kaynaşırım','Uzaktan gözlemlerim önce','Kendimi kanıtlarım','Kim kimle ne yapmış öğrenirim']},
  {id:'wq10',q:'Arkadaşın zor durumda, senden para istiyor.',o:['Son paramı bile veririm','Yok diyip geçiştiririm','Ne zaman ödeyeceğini sorarım','Param yoksa bile çözüm bulurum']},
  {id:'wq11',q:'Biri sana iftira attı.',o:['Döverim','Onun hakkında daha büyük şeyler ortaya çıkarırım','Gerçeği sakinçe açıklarım','Bağırır çağırırım']},
  {id:'wq12',q:'Hayatta en çok neye değer verirsin?',o:['Aşk ve sevgi','Para ve güç','Özgürlük ve deneyim','Dostluk ve güven']},
  {id:'wq13',q:'Bir işe başlarken tarzın ne?',o:['Plan yapar, disiplinli çalışırım','Son dakikaya bırakırım','Düşünmeden atlarım','Ekip kurar, dağıtırım']},
  {id:'wq14',q:'Gece geç saatte kapın çalındı.',o:['Açarım, kim olursa olsun','Saklanırım, açmam','Kim olduğunu sorarım','Yanıma bir şey alıp açarım']},
  {id:'wq15',q:'Kurallar hakkında ne düşünürsün?',o:['Kurallar çiğnenmek için var','Doğru kurallara uyarım','Kurallar benim için geçerli değil','Düzen şart, uyarım']},
  {id:'wq16',q:'Biri seni kızdırdığında?',o:['Anında patlarım','Hiç belli etmem','İntikamımı soğuk yerim','Affederim genellikle']},
  {id:'wq17',q:'Zengin olsan ilk ne yaparsın?',o:['Lüks hayat, araba, ev','Garajı arabalarla doldururum','Ailem ve dostlarıma yardım','Sadece kendime harcarım']},
  {id:'wq18',q:'Tehlikeli bir görev teklif edildi.',o:['Kabul, risk benim işim','Kesinlikle hayır','Detaylara bağlı ama heyecanlıyım','Kazancı neyse ona göre']},
  {id:'wq19',q:'İnsanlar seni nasıl tanımlar?',o:['Eğlenceli ve çekici','Tahmin edilemez','Her şeyi bilen','Sahiplenici ve kıskanç']},
  {id:'wq20',q:'Son sözün ne olurdu?',o:['Ben yapmadım!','Bir daha deneyelim!','Seni seviyorum','Eee şimdi ne olacak?']},
];
let memQs=[
  {id:'mq1',q:'EightBornV sunucusunun türü nedir?',o:['FiveM RP','Minecraft','CS2','Valorant'],ci:0},
  {id:'mq2',q:'CK ne anlama gelir?',o:['Cool Kid','Character Kill','Crew King','Crime King'],ci:1},
  {id:'mq3',q:'Sunucuda kaç faction bulunur?',o:['3','5','7','10'],ci:1},
  {id:'mq4',q:'Polis teşkilatının kısa adı nedir?',o:['LSPD','BCSO','FBI','SAHP'],ci:0},
  {id:'mq5',q:'Illegal iş yapan gruplara ne denir?',o:['Çete','Mafya','İkisi de','Hiçbiri'],ci:2},
  {id:'mq6',q:'Hastanede çalışan karakterler ne yapar?',o:['Tedavi','Silah satar','Araba tamir','Yemek pişirir'],ci:0},
  {id:'mq7',q:'RP sunucusunda /me komutu ne işe yarar?',o:['Mesaj atar','Aksiyon tanımlar','Silah çeker','Araç çağırır'],ci:1},
  {id:'mq8',q:'PowerGaming ne demektir?',o:['Güçlü oynamak','Gerçek dışı güç kullanmak','Hızlı oynamak','PvP yapmak'],ci:1},
  {id:'mq9',q:'MetaGaming ne demektir?',o:['RP dışı bilgiyi RP de kullanmak','Çok oyun oynamak','Meta silah kullanmak','Takım kurmak'],ci:0},
  {id:'mq10',q:'VDM ne anlama gelir?',o:['Very Dangerous Move','Vehicle Death Match','Virtual Damage Mode','Video Death Match'],ci:1},
  {id:'mq11',q:'RDM ne anlama gelir?',o:['Random Death Match','Real Damage Mode','Role Death Match','Rapid Death Match'],ci:0},
  {id:'mq12',q:'NLR (New Life Rule) ne demektir?',o:['Yeni hayat kuralı','Yeni level kuralı','Yeni bölge kuralı','Yeni silah kuralı'],ci:0},
  {id:'mq13',q:'RP sunucusunda /ooc ne demektir?',o:['Out of Character','Only Online Chat','Open Other Channel','Over Our Crew'],ci:0},
  {id:'mq14',q:'Fail RP ne demektir?',o:['Kötü roleplay yapmak','Başarısız olmak','Oyun kaybetmek','Sunucudan atılmak'],ci:0},
  {id:'mq15',q:'Sunucuda beyaz listeye alınmak ne demektir?',o:['Whitelist onayı almak','Admin olmak','VIP almak','Ban yemek'],ci:0},
  {id:'mq16',q:'Gang bölgesi ele geçirmeye ne denir?',o:['Turf War','Gang Fight','Street Battle','Hood Capture'],ci:0},
  {id:'mq17',q:'EMS ne demektir?',o:['Emergency Medical Services','Elite Military Squad','Electronic Mail System','Extra Mission Squad'],ci:0},
  {id:'mq18',q:'RP de karakter öldüğünde ne olur?',o:['CK alır','Respawn olur','Ban yer','Hiçbiri'],ci:0},
  {id:'mq19',q:'Sunucuda /do komutu ne işe yarar?',o:['Çevre tanımı yapar','Dans eder','Dövüş başlatır','Araç sürer'],ci:0},
  {id:'mq20',q:'IC ne demektir?',o:['In Character','Internet Chat','Ice Cream','I See'],ci:0},
];

// Score integrity - simple checksum
function scoreChecksum(userId, score) {
  var s = userId + '_' + score + '_ebv2025';
  var h = 0;
  for (var i = 0; i < s.length; i++) { h = ((h << 5) - h) + s.charCodeAt(i); h = h & h; }
  return Math.abs(h).toString(36);
}
