
// ═══════════════════════════════════════════════════
// KARAKTER HİKAYESİ OLUŞTURUCU — Varsayılan İçerik Havuzu (seed)
// Bu havuz init'te story_* tablolarına yüklenir; admin panelden düzenlenebilir.
//
// Soru biçimi: Q(category, text, opt, opt, opt, opt)
// Seçenek biçimi: O(text, frag, cr, tr, ld, sm, ch)
//   frag : hikâyeye eklenecek anlatı parçası — {N} ad-soyad ile değişir, küçük harf başlar
//   cr   : suç eğilimi  (-3..+3)   tr : güvenilirlik (-3..+3)   ld : liderlik (-3..+3)
//   sm   : zekâ (-3..+3)           ch : kaos (-3..+3)
//
// Kategoriler → hikâye bölümleri:
//   cocukluk    → Çocukluk          genclik   → Gençlik
//   donum       → İlk Dönüm Noktası kariyer   → Kariyer
//   sosyal      → Dostları ve Düşmanları       kisilik → Kişiliği
//   gelecek     → Gelecek Hedefleri
// ═══════════════════════════════════════════════════
function O(t, frag, cr, tr, ld, sm, ch) { return { t: t, frag: frag, cr: cr|0, tr: tr|0, ld: ld|0, sm: sm|0, ch: ch|0 }; }
function Q(cat, text, a, b, c, d) { return { cat: cat, q: text, opts: [a, b, c, d] }; }

var STORYGEN_SEED = {
  categories: [
    { key: 'cocukluk', name: 'Çocukluk', ord: 1 },
    { key: 'genclik',  name: 'Gençlik',  ord: 2 },
    { key: 'donum',    name: 'Kırılma Noktaları', ord: 3 },
    { key: 'kariyer',  name: 'Kariyer',  ord: 4 },
    { key: 'sosyal',   name: 'Sosyal Hayat', ord: 5 },
    { key: 'kisilik',  name: 'Karakter Özellikleri', ord: 6 },
    { key: 'gelecek',  name: 'Gelecek Hedefleri', ord: 7 }
  ],
  // Bir oynanışta her kategoriden kaç soru çekileceği (toplam 10)
  plan: { cocukluk: 2, genclik: 2, donum: 1, kariyer: 1, sosyal: 1, kisilik: 2, gelecek: 1 },
  questions: [
    // ───────────────────────── ÇOCUKLUK (16) ─────────────────────────
    Q('cocukluk', 'Nasıl bir ailede büyüdü?',
      O('Kalabalık ama yoksul bir ailede', 'kalabalık ama yoksul bir evde, ekmeğini kardeşleriyle paylaşarak büyüdü', 1, 1, 0, 0, 0),
      O('Zengin ama sevgisiz bir ailede', 'zengin ama soğuk bir konakta, parası bol sevgisi az bir çocukluk geçirdi', 0, -1, 1, 1, 0),
      O('Tek ebeveynli, mücadeleci bir evde', 'tek başına direnen bir ebeveynin yanında, erken yaşta sorumluluk öğrenerek büyüdü', 0, 1, 1, 1, 0),
      O('Suça bulaşmış bir ailenin içinde', 'eli kanlı işlere bulaşmış bir ailenin gölgesinde, daha küçükken kuralların nasıl çiğnendiğini gördü', 2, -1, 0, 0, 1)),
    Q('cocukluk', 'Çocukken en büyük korkusu neydi?',
      O('Yalnız kalmak', 'çocukken en çok yalnız kalmaktan korkardı; bu korku onu insanlara bağlanmaya itti', 0, 1, 0, 0, 0),
      O('Babasının öfkesi', 'evdeki öfkeden korkarak büyüdü, sessiz olmayı ve gözlemlemeyi erken öğrendi', 0, 0, 0, 1, 0),
      O('Aç kalmak', 'aç kalma korkusu içine işledi; ileride parayla kurduğu ilişki hep bu korkuyla şekillendi', 1, 0, 0, 0, 0),
      O('Hiçbir şeyden korkmazdı', 'küçük yaşta bile gözünü budaktan sakınmazdı, korku ona yabancı bir duyguydu', 1, -1, 1, 0, 2)),
    Q('cocukluk', 'Okul hayatı nasıldı?',
      O('Sınıfın en zekisiydi', 'okulda sınıfın en zekisiydi, öğretmenleri ondan umutluydu', 0, 1, 1, 3, 0),
      O('Sürekli kavgaya karışırdı', 'okul yıllarını koridor kavgalarıyla geçirdi, otoriteyle hiç anlaşamadı', 1, -1, 1, 0, 2),
      O('Görünmez bir öğrenciydi', 'kalabalıkta kaybolan, kimsenin adını hatırlamadığı sessiz bir öğrenciydi', 0, 0, -1, 1, 0),
      O('Okulu hiç sevmedi, sık kaçtı', 'okuldan sık kaçar, hayatı sokakta öğrenmeyi tercih ederdi', 1, -1, 0, 1, 1)),
    Q('cocukluk', 'Çocukken kime hayrandı?',
      O('Mahallenin sözü geçen abisine', 'mahallenin sözü geçen abisine hayrandı, güç ve saygının tadını ondan öğrendi', 1, 0, 2, 0, 0),
      O('Çalışkan ve dürüst babasına', 'alın teriyle geçinen babasını örnek aldı, dürüstlüğü ondan miras aldı', 0, 2, 0, 0, 0),
      O('Filmlerdeki kanun kaçaklarına', 'beyazperdedeki kanun kaçaklarına özendi, kuralları çiğnemenin cazibesine kapıldı', 2, -1, 1, 0, 1),
      O('Kimseye, kendi yolunu çizdi', 'kimseyi örnek almadı; daha o yaşta kendi yolunu kendi çizmeye karar verdi', 0, 0, 2, 1, 1)),
    Q('cocukluk', 'İlk parasını nasıl kazandı?',
      O('Simit/gazete satarak', 'küçük elleriyle simit, gazete satarak ilk parasını kazandı; emeğin değerini erken öğrendi', 0, 2, 0, 0, 0),
      O('Küçük hırsızlıklarla', 'ilk parası küçük hırsızlıklardan geldi; risk almak ona heyecan verdi', 2, -2, 0, 1, 1),
      O('Komşulara işler yaparak', 'komşulara ufak işler yaparak harçlığını çıkardı, herkesin güvenini kazandı', 0, 2, 1, 0, 0),
      O('Kumar ve bahisle', 'daha çocukken kâğıt ve zarla tanıştı; şansı denemek kanına işledi', 1, -1, 0, 1, 2)),
    Q('cocukluk', 'Çocukluğunda en çok ne eksikti?',
      O('Sevgi ve ilgi', 'çocukluğunda sevgi açlığı çekti; bu boşluğu ileride güçle doldurmaya çalıştı', 1, 0, 1, 0, 1),
      O('Para ve güvence', 'sürekli kıtlık içinde büyüdü; güvende olmak en büyük hayali oldu', 1, 0, 0, 0, 0),
      O('Özgürlük', 'baskı altında büyüdü; özgürlük tutkusu onu hep sınırların ötesine itti', 0, 0, 1, 0, 2),
      O('Bir rol model', 'yol gösterecek kimsesi olmadı; her şeyi deneme yanılmayla öğrendi', 0, 0, 1, 1, 0)),
    Q('cocukluk', 'Hangi mahallede büyüdü?',
      O('Şehrin tehlikeli varoşlarında', 'şehrin en sert varoşlarında büyüdü; ayakta kalmak başlı başına bir okuldu', 2, -1, 1, 0, 1),
      O('Sakin bir taşra kasabasında', 'sakin bir kasabada büyüdü; şehrin kaosuna sonradan karıştı', 0, 1, 0, 0, -1),
      O('Lüks ama soğuk bir muhitte', 'yüksek duvarlı lüks bir muhitte büyüdü; dışarıdaki hayata hep meraklıydı', 0, 0, 1, 1, 0),
      O('Liman ve sanayi bölgesinde', 'liman ve sanayinin gürültüsünde büyüdü; çalışmayı ve dümen çevirmeyi birlikte öğrendi', 1, 0, 0, 1, 0)),
    Q('cocukluk', 'Çocukken en yakın sırdaşı kimdi?',
      O('Sokak köpeği', 'tek sırdaşı bir sokak köpeğiydi; sadakatin ne demek olduğunu ondan öğrendi', 0, 1, 0, 0, 0),
      O('Kardeşi', 'kardeşi hem dostu hem sırdaşıydı; aile bağı en güçlü zırhı oldu', 0, 1, 1, 0, 0),
      O('Hayali bir arkadaş', 'yalnızlığını hayali bir arkadaşla doldururdu; iç dünyası hep zengindi', 0, 0, 0, 1, 1),
      O('Kimse, içine kapanıktı', 'kimseye açılmazdı; sırlarını yalnız kendine saklamayı küçükken öğrendi', 0, -1, 0, 1, 0)),

    // ───────────────────────── GENÇLİK (16) ─────────────────────────
    Q('genclik', 'İlk suçunu işledi mi?',
      O('Evet, küçük bir hırsızlık', 'gençliğinde ilk suçu küçük bir hırsızlık oldu; o gece geri dönüşü olmayan bir kapı araladı', 2, -1, 0, 1, 1),
      O('Hayır, hep temiz kaldı', 'her fırsata rağmen elini kirletmedi; temiz kalmayı bir onur meselesi yaptı', -1, 2, 0, 0, -1),
      O('Evet, ama başkası için', 'ilk suçunu kendisi için değil, sevdiği biri için işledi; sadakati kuralların önüne geçti', 1, 1, 1, 0, 1),
      O('Büyük bir işe karıştı', 'gençken büyük bir işin içinde buldu kendini; küçük adımları atlayıp derin sulara daldı', 3, -2, 1, 0, 2)),
    Q('genclik', 'İlk aşkı nasıl bitti?',
      O('İhanetle', 'ilk aşkı ihanetle bitti; o günden sonra kimseye kolay güvenmedi', 0, -1, 0, 1, 0),
      O('Ayrı düştüler, kader ayırdı', 'sevdiğiyle yollar kaderin zoruyla ayrıldı; içinde tatlı bir hüzün kaldı', 0, 1, 0, 0, 0),
      O('Onun yüzünden suça bulaştı', 'ilk aşkı onu karanlık bir yola sürükledi; aşkla suç o yıllarda iç içe geçti', 2, -1, 0, 0, 1),
      O('Hiç âşık olmadı', 'kalbini hiç kaptırmadı; duygularını hep kontrol altında tutmayı seçti', 0, 0, 1, 1, 0)),
    Q('genclik', 'Gençliğinde nasıl biriydi?',
      O('Asi ve kontrolsüz', 'asi ve kontrolsüz bir gençti; kuralları çiğnemek ona nefes aldırırdı', 1, -1, 1, 0, 3),
      O('Hırslı ve hesaplı', 'hırslıydı ama her adımını hesaplardı; aceleci asla olmadı', 1, 0, 2, 2, 0),
      O('Sessiz ve gözlemci', 'sessizce izler, herkesin zaafını öğrenirdi; gücü gürültüde değil bilgide arardı', 1, 0, 1, 3, 0),
      O('Eğlenceye düşkün, savruk', 'günü yaşar, yarını düşünmezdi; eğlence ve risk peşinde savrulurdu', 1, -1, 0, 0, 2)),
    Q('genclik', 'İlk büyük hayal kırıklığı neydi?',
      O('Güvendiği birinin ihaneti', 'en güvendiği kişi onu sattı; bu ihanet karakterini çelikleştirdi', 1, -1, 1, 1, 0),
      O('Bir hayalin suya düşmesi', 'yıllarca kurduğu hayal bir anda yıkıldı; küllerinden yeni bir hedef doğdu', 0, 0, 1, 1, 0),
      O('Ailesini kaybetmek', 'ailesini erken kaybetti; bu kayıp onu zamanından önce büyüttü', 1, 0, 1, 0, 1),
      O('Adaletin işlememesi', 'haklıyken haksız çıktı; sisteme olan inancını o gün yitirdi', 2, -1, 1, 1, 1)),
    Q('genclik', 'Gençken parayı nasıl görürdü?',
      O('Özgürlüğün anahtarı', 'parayı özgürlüğün anahtarı sayardı; ne pahasına olursa olsun peşinden koştu', 1, 0, 1, 1, 0),
      O('Güç ve saygının kaynağı', 'para ona güç ve saygı demekti; cüzdanı doldukça sözü daha çok geçti', 1, 0, 2, 0, 1),
      O('Gerekli ama kirli bir şey', 'parayı gerekli ama kirli bir araç olarak gördü; ona köle olmamaya çalıştı', 0, 1, 0, 1, 0),
      O('Kumarda yanan bir kâğıt', 'eline geçen parayı kolay harcardı; bugün zengin yarın meteliksizdi', 1, -1, 0, 0, 2)),
    Q('genclik', 'İlk silahını ne zaman tuttu?',
      O('Kendini korumak için genç yaşta', 'kendini korumak için genç yaşta silah tuttu; o ağırlık elinde hep kaldı', 2, 0, 1, 0, 1),
      O('Hiç silah tutmadı', 'silahtan hep uzak durdu; gücünü başka yollarda aradı', -1, 1, 0, 1, -1),
      O('Bir abinin emriyle', 'bir abinin emriyle ilk kez tetiğe dokundu; o gün biat etmenin bedelini öğrendi', 2, -1, 0, 0, 1),
      O('Merakından, sonra bağımlısı oldu', 'merakla başladı, sonra silahsız adım atamaz oldu; tehlike onun konfor alanı oldu', 2, -1, 1, 0, 2)),
    Q('genclik', 'Gençliğinde en çok nereye giderdi?',
      O('Yeraltı kulüpleri ve kumarhaneler', 'gecelerini yeraltı kulüplerinde ve kumarhanelerde geçirdi; şehrin karanlık yüzünü ezberledi', 1, -1, 1, 1, 2),
      O('Spor salonu ve dövüş kulübü', 'spor salonunda demir attı, ringde sertleşti; bedeni de iradesi de güçlendi', 1, 0, 1, 0, 1),
      O('Kütüphane ve kahvehaneler', 'kütüphane ve kahvehanelerde takılır, herkesi dinler, her şeyi öğrenirdi', 0, 1, 1, 3, 0),
      O('Sokak ve garajlar', 'sokakta ve garajlarda büyüdü; motor sesi ve asfalt onun müziğiydi', 1, 0, 1, 1, 1)),
    Q('genclik', 'İlk kez nasıl ün kazandı?',
      O('Korkusuzluğuyla', 'korkusuzluğuyla nam saldı; kimsenin göze alamadığını o yapardı', 2, 0, 2, 0, 2),
      O('Verdiği sözü tutmasıyla', 'sözünün eri olmasıyla tanındı; el sıkışması senet sayılırdı', 0, 3, 1, 0, 0),
      O('Kurnazlığıyla', 'kurnazlığıyla ün yaptı; en çıkmaz işten bile sıyrılmayı bilirdi', 1, 0, 1, 2, 1),
      O('Acımasızlığıyla', 'acımasızlığıyla korku saldı; adı anıldığında ortam sessizleşirdi', 3, -2, 1, 0, 2)),

    // ───────────────────────── KIRILMA NOKTALARI (14) ─────────────────────────
    Q('donum', 'Hayatını değiştiren olay neydi?',
      O('Sevdiği birini kaybetmesi', 'her şeyi değiştiren an, sevdiği birini kaybettiği gün oldu; o günden sonra bambaşka biri oldu', 1, 0, 1, 0, 1),
      O('Hapse girmesi', 'parmaklıklar ardında geçen zaman onu kökten değiştirdi; içeride hem düşman hem dost edindi', 2, -1, 1, 1, 1),
      O('Büyük bir ihanete uğraması', 'en yakınının ihaneti onu yeniden doğurdu; artık kimseye sırtını dönmüyordu', 1, -1, 1, 1, 1),
      O('Beklenmedik bir servete konması', 'bir anda eline geçen servet kaderini değiştirdi; güç ve sorumluluk aynı anda omzuna bindi', 0, 0, 2, 1, 1)),
    Q('donum', 'En büyük pişmanlığı nedir?',
      O('Güvenilmez birine güvenmek', 'en büyük pişmanlığı yanlış kişiye güvenmiş olmaktı; bu ders ona pahalıya mal oldu', 0, 0, 1, 1, 0),
      O('Bir dostunu yarı yolda bırakmak', 'zor günde bir dostunu yalnız bırakmıştı; vicdanı bunu hiç affetmedi', 1, -1, 0, 0, 1),
      O('Fırsatı tepip kaçırmak', 'hayatının fırsatını tereddütle kaçırdı; bir daha asla duraksamamaya yemin etti', 0, 0, 1, 1, 0),
      O('Hiçbir şeyden pişman değil', 'hiçbir şeyden pişman olmadı; yaptığı her hatayı bir basamak saydı', 1, -1, 1, 0, 1)),
    Q('donum', 'Bir gün her şeyini kaybetseydi ne yapardı?',
      O('Sıfırdan, sabırla kurardı', 'her şeyini kaybetse sıfırdan, sabırla kurardı; yıkım onu yıldırmazdı', 0, 1, 1, 1, 0),
      O('İntikam için ayağa kalkardı', 'kaybettiklerinin hesabını sormak için ayağa kalkardı; intikam yakıtı olurdu', 2, -1, 1, 0, 2),
      O('Şehri terk eder, kaybolurdu', 'her şey bittiğinde sessizce kaybolmayı seçerdi; yeni bir yerde yeni bir isim olurdu', 1, 0, 0, 1, 0),
      O('Kötü yola saparak hızlı toparlardı', 'dibe vurduğunda en kısa yoldan, kuralları çiğneyerek toparlardı', 3, -2, 1, 0, 2)),
    Q('donum', 'Onu en çok ne öfkelendirir?',
      O('İhanet', 'ihanet onu küplere bindirir; sadakatsizliği asla unutmaz', 1, 0, 1, 0, 1),
      O('Haksızlık', 'haksızlık karşısında durup bekleyemez; öfkesi adalet duygusundan beslenir', 1, 1, 1, 0, 1),
      O('Saygısızlık', 'saygısızlığa tahammülü yoktur; itibarına dokunanı affetmez', 2, -1, 2, 0, 1),
      O('Hiçbir şey, soğukkanlıdır', 'kolay kolay öfkelenmez; sakinliği en güçlü silahıdır', 0, 1, 1, 2, -1)),
    Q('donum', 'Hayatındaki en karanlık an hangisiydi?',
      O('Birini incitmek zorunda kaldığı an', 'birini incitmek zorunda kaldığı o an içinde bir yara olarak kaldı', 2, 0, 0, 0, 1),
      O('Tamamen yalnız kaldığı gece', 'herkesin onu terk ettiği o gece ruhunun en dibini gördü', 1, 0, 0, 1, 0),
      O('Bir sınırı geçtiği an', 'bir kez bir sınırı geçince geri dönüşün olmadığını anladı', 3, -2, 1, 0, 2),
      O('Sevdiğinin gözündeki hayal kırıklığı', 'sevdiğinin gözündeki hayal kırıklığı en büyük cezası oldu', 0, 1, 0, 0, 0)),

    // ───────────────────────── KARİYER (16) ─────────────────────────
    Q('kariyer', 'İlk mesleği neydi?',
      O('Garson/komi', 'hayata bir lokantada komilik yaparak atıldı; insan sarrafı olmayı orada öğrendi', 0, 1, 0, 1, 0),
      O('Oto tamircisi', 'elleri yağ kokan bir tamirhanede pişti; her motorun da her insanın da nesinden tutulacağını bilirdi', 0, 1, 0, 1, 0),
      O('Küçük çaplı satıcı', 'sokakta alım satımla başladı; pazarlık ve ikna onun ilk silahı oldu', 1, 0, 1, 1, 0),
      O('Kuryelik (her türden paket)', 'kuryelikle başladı; taşıdığı paketlerin hepsi masum değildi, şehri avucu gibi tanıdı', 2, -1, 0, 1, 1)),
    Q('kariyer', 'Hayalindeki iş neydi?',
      O('Kendi işinin patronu olmak', 'tek hayali kendi işinin patronu olmaktı; kimseden emir almak istemiyordu', 0, 0, 2, 1, 0),
      O('Şehrin en büyük ismi olmak', 'şehrin en büyük ismi olmayı hayal etti; gölgesi her sokağa düşsün istedi', 2, -1, 2, 0, 1),
      O('Rahat ve huzurlu bir hayat', 'tek istediği rahat, huzurlu bir hayattı; ne var ki şehir onu rahat bırakmadı', 0, 1, 0, 0, -1),
      O('Bir efsane olarak anılmak', 'öldükten sonra bile anılan bir efsane olmak istedi; sıradanlık ona göre değildi', 1, 0, 2, 1, 1)),
    Q('kariyer', 'Şu anki mesleğine nasıl başladı?',
      O('Mecburiyetten, başka çaresi yoktu', 'bugünkü işine mecburiyetten girdi; başka kapı çalmadığı için bu kapıdan girdi', 1, 0, 0, 0, 0),
      O('Bir ustanın çırağı olarak', 'işin inceliklerini bir ustanın yanında öğrendi; çıraklıktan ustalığa terledi', 0, 1, 1, 1, 0),
      O('Doğru anda doğru yerde olarak', 'şans kapıyı çaldığında hazırdı; doğru anda doğru yerde olmayı bildi', 1, 0, 1, 2, 0),
      O('Birini saf dışı bırakarak', 'önündekini saf dışı bırakıp koltuğa oturdu; yükselişi başkalarının düşüşü oldu', 3, -2, 2, 1, 1)),
    Q('kariyer', 'İşini nasıl yürütür?',
      O('Sözüne ve güvene dayanarak', 'işini söz ve güven üzerine kurdu; bir kez verdiği sözü asla bozmaz', 0, 3, 1, 1, 0),
      O('Korku ve baskıyla', 'işini korkuyla yürütür; karşısındakini ezmeyi bir yöntem sayar', 3, -2, 2, 0, 1),
      O('Zekâ ve stratejiyle', 'her işi satranç gibi oynar; rakibini hamle yapmadan çözer', 1, 0, 1, 3, 0),
      O('Esneklik ve fırsatçılıkla', 'rüzgâra göre yelken açar; her durumdan kâr çıkarmayı bilir', 2, -1, 1, 2, 1)),
    Q('kariyer', 'Para kazanma yöntemi nedir?',
      O('Dürüst emek', 'ekmeğini alın teriyle kazanır; haram lokmadan uzak durur', -1, 3, 0, 0, -1),
      O('Gri bölgede ticaret', 'yasanın grisinde iş yapar; ne tam içeride ne tam dışarıda durur', 2, 0, 1, 2, 1),
      O('Açıkça yasa dışı işler', 'parasını açıkça yasa dışı işlerden kazanır; risk onun günlük ekmeğidir', 3, -2, 1, 0, 2),
      O('Başkalarının parasını yöneterek', 'kendi parasını değil, başkalarının parasını yönetir; asıl gücü buradan gelir', 1, 0, 2, 2, 0)),
    Q('kariyer', 'İş dünyasında nasıl tanınır?',
      O('Güvenilir bir ortak olarak', 'iş çevresinde güvenilir bir ortak olarak tanınır; ona sırt yaslanır', 0, 3, 1, 1, 0),
      O('Tehlikeli bir rakip olarak', 'rakipleri ondan çekinir; karşısına çıkmak göze alınacak bir iştir', 2, -1, 2, 1, 1),
      O('Kurnaz bir tilki olarak', 'kurnaz bir tilki olarak bilinir; en kapalı kapıyı bile aralamayı bilir', 1, 0, 1, 3, 1),
      O('Öngörülemez biri olarak', 'ne yapacağı asla kestirilemez; bu belirsizlik en büyük kozudur', 1, -1, 1, 1, 2)),
    Q('kariyer', 'Bir anlaşma bozulursa ne yapar?',
      O('Önce konuşmayı dener', 'anlaşma bozulunca önce masaya oturur; kan dökmeden çözmeyi yeğler', 0, 2, 1, 1, 0),
      O('Misillemeyle cevap verir', 'sözünden dönülünce sert misilleme yapar; zayıf görünmeye tahammülü yoktur', 3, -1, 1, 0, 2),
      O('Sessizce intikam planlar', 'belli etmeden bekler, sonra hesabı faiziyle sorar', 2, -1, 1, 2, 1),
      O('Zararı keser, yoluna bakar', 'zararına razı olup defteri kapatır; köprüleri yakmayı sevmez', 0, 1, 0, 2, 0)),
    Q('kariyer', 'Şehirde hangi alanda söz sahibi?',
      O('Gece hayatı ve kulüpler', 'gece hayatında sözü geçer; kulüplerin ışıkları onun bilgisi dışında yanmaz', 1, 0, 2, 1, 1),
      O('Sokak ve mahalle işleri', 'sokağın diline hâkimdir; mahalle onun sözünü dinler', 1, 1, 2, 0, 1),
      O('Ticaret ve para akışı', 'paranın akışına yön verir; rakamların arkasındaki gerçek güç odur', 1, 0, 1, 3, 0),
      O('Bilgi ve sırlar', 'asıl sermayesi bilgidir; kimin nerede ne yaptığını herkesten önce bilir', 1, 0, 1, 3, 1)),

    // ───────────────────────── SOSYAL HAYAT (12) ─────────────────────────
    Q('sosyal', 'En yakın dostunu nasıl tanıdı?',
      O('Birlikte zor bir günden geçerek', 'en yakın dostunu zor bir günde tanıdı; ateşten birlikte geçtiler, bağları çelikleşti', 0, 2, 1, 0, 0),
      O('Bir kavgada karşı taraftayken', 'en iyi dostuyla bir kavgada düşman olarak tanıştı; sonra silah arkadaşı oldular', 1, 0, 1, 0, 1),
      O('Çocukluktan beri kan kardeşi', 'dostluğu çocukluğa dayanır; kan kardeşi gibi büyüdüler, ayrılmadılar', 0, 2, 1, 0, 0),
      O('Bir işbirliği uğruna', 'dostluğu ortak bir çıkarla başladı; menfaat zamanla sadakate dönüştü', 1, 0, 1, 1, 0)),
    Q('sosyal', 'En büyük düşmanı nasıl oluştu?',
      O('İhanetin intikamıyla', 'en büyük düşmanı, ona ihanet eden eski bir dostudur; o yara hiç kapanmadı', 1, -1, 1, 0, 1),
      O('Aynı tahtı istedikleri için', 'düşmanlığı bir rekabetten doğdu; ikisi de aynı tahtı istedi, biri devrilecekti', 1, 0, 2, 1, 1),
      O('Bir hata yüzünden kazara', 'düşmanını istemeden kazandı; küçük bir hata büyük bir husumete dönüştü', 0, 0, 0, 0, 1),
      O('Bir kan davası yüzünden', 'kökü eskiye dayanan bir kan davası onu ömürlük bir düşmanla bağladı', 2, -1, 1, 0, 1)),
    Q('sosyal', 'İnsanlara nasıl yaklaşır?',
      O('Önce güvenir, sonra sorgular', 'insanlara önce elini uzatır; aldatılana kadar herkese bir şans verir', 0, 2, 0, 0, 0),
      O('Herkese mesafeli ve temkinli', 'kimseyi kolay içeri almaz; mesafe onun korunağıdır', 1, 0, 1, 1, 0),
      O('Çıkarına göre yakınlaşır', 'kime ne kadar yaklaşacağını çıkarına göre ayarlar; her dostluğun bir hesabı vardır', 1, -1, 1, 2, 0),
      O('Sıcakkanlı ve girişken', 'sıcakkanlıdır, kalabalığın ortasında parlar; insanları kolayca etrafında toplar', 0, 1, 2, 0, 1)),
    Q('sosyal', 'Bir dostu zor durumda kalsa?',
      O('Ne pahasına olursa olsun yardım eder', 'bir dostu için ateşe atlar; bedeli ne olursa olsun yanında durur', 1, 2, 1, 0, 1),
      O('Aklıselim davranır, riski tartar', 'yardım etmeden önce riski tartar; duygularıyla değil aklıyla hareket eder', 0, 1, 1, 2, 0),
      O('Karşılığını bekleyerek yardım eder', 'yardım eder ama bir gün karşılığını ister; her iyiliği deftere yazar', 1, -1, 1, 1, 0),
      O('Kendi postunu önce düşünür', 'önce kendi canının derdine düşer; gemi batarken ilk o atlar', 1, -2, 0, 1, 1)),

    // ───────────────────────── KARAKTER ÖZELLİKLERİ (16) ─────────────────────────
    Q('kisilik', 'En büyük zaafı nedir?',
      O('Sevdiklerini fazla korumak', 'en büyük zaafı sevdiklerine olan düşkünlüğüdür; onlara dokunan herkesi karşısında bulur', 1, 1, 1, 0, 1),
      O('Öfkesini kontrol edememek', 'öfkesi en zayıf noktasıdır; bir anlık sinir yıllarını yakabilir', 2, -1, 0, 0, 2),
      O('Aşırı güvenmek', 'fazla güvenmek başına iş açar; herkesi kendi gibi sanmak ona pahalıya patlar', 0, 1, 0, -1, 0),
      O('Para ve güç hırsı', 'doymak bilmeyen hırsı en büyük zaafıdır; yeterince hiçbir zaman yeterli değildir', 2, -1, 1, 0, 1)),
    Q('kisilik', 'En büyük gücü nedir?',
      O('Asla pes etmemesi', 'en büyük gücü asla pes etmemesidir; yıkılsa da her seferinde ayağa kalkar', 0, 1, 2, 0, 0),
      O('Soğukkanlılığı', 'en büyük gücü soğukkanlılığıdır; herkes panikteyken o sakin kalır', 0, 1, 2, 2, -1),
      O('Keskin zekâsı', 'en büyük gücü zekâsıdır; kaba kuvvetin çözemediğini aklıyla çözer', 0, 0, 1, 3, 0),
      O('İnsanları etkileme yeteneği', 'en büyük gücü insanları peşinden sürükleme yeteneğidir; sözüyle kapılar açılır', 1, 0, 3, 1, 0)),
    Q('kisilik', 'Güven problemi var mı?',
      O('Evet, kimseye tam güvenmez', 'kimseye tam güvenmez; sırtını hep sağlam bir duvara yaslar', 1, -1, 1, 1, 0),
      O('Hayır, açık ve dürüsttür', 'açık ve dürüsttür; ne düşünüyorsa onu söyler, dolandırmayı sevmez', -1, 2, 1, 0, 0),
      O('Sadece kanıtlanmış kişilere güvenir', 'güveni emekle kazanılır; ateşten geçmemiş kimseye sırrını vermez', 0, 1, 1, 2, 0),
      O('Çok kolay güvenir, sık yanılır', 'kolay güvenir, sık yanılır; iyi niyeti bazen başına bela olur', 0, 1, -1, -1, 0)),
    Q('kisilik', 'Baskı altında nasıl davranır?',
      O('Buz gibi sakin kalır', 'baskı altında buz gibi olur; kriz anı onun en parladığı andır', 1, 1, 2, 2, -1),
      O('Saldırganlaşır', 'sıkışınca saldırganlaşır; köşeye sıkışan bir hayvan gibi tehlikelidir', 3, -1, 1, 0, 2),
      O('Hızlı ve yaratıcı çözüm bulur', 'baskı onu yaratıcı kılar; en dar anda en sıra dışı çıkışı bulur', 1, 0, 1, 3, 1),
      O('Donar, karar veremez', 'baskı altında bazen donup kalır; en kötü anda tereddüt eder', 0, 0, -1, 0, 1)),
    Q('kisilik', 'Liderlik tarzı nasıl?',
      O('Önden giden, örnek olan lider', 'önden giden bir liderdir; yapılmasını istediği şeyi önce kendi yapar', 1, 1, 3, 1, 0),
      O('Korkutarak yöneten lider', 'korkuyla yönetir; itaat sevgiden değil çekinceden gelir', 3, -2, 2, 0, 1),
      O('Akıl veren, stratejist lider', 'sahnenin arkasından yönetir; planı kurar, gerisini başkaları oynar', 1, 0, 2, 3, 0),
      O('Lider değil, yalnız kurttur', 'kimseyi yönetmek istemez; tek başına çalışan bir kurttur', 1, 0, 0, 1, 1)),
    Q('kisilik', 'Bir karar verirken neye güvenir?',
      O('İçgüdülerine', 'kararlarını içgüdüleriyle verir; içinden gelen sesi hiç yanıltmadı', 1, 0, 1, 0, 1),
      O('Mantık ve hesaba', 'her kararı mantık süzgecinden geçirir; duygu işin içine karışmaz', 0, 1, 1, 3, -1),
      O('Tecrübesine', 'tecrübesine güvenir; aynı tuzağa iki kez düşmemeyi öğrenmiştir', 0, 1, 1, 2, 0),
      O('Anlık hislerine', 'anlık hisleriyle hareket eder; bu onu hem cesur hem öngörülemez yapar', 1, -1, 0, 0, 2)),
    Q('kisilik', 'Yalan söyler mi?',
      O('Asla, sözü senettir', 'yalan söylemez; sözü senet, lafı kanun sayılır', -1, 3, 1, 0, 0),
      O('Gerektiğinde, ustaca', 'gerektiğinde ustaca yalan söyler; doğruyu ne zaman saklayacağını iyi bilir', 1, -1, 1, 2, 0),
      O('Sürekli, herkese', 'doğruyu nadiren söyler; herkese ayrı bir maske takar', 2, -3, 1, 1, 1),
      O('Sadece kendini korumak için', 'yalnız kendini korumak için yalana sığınır; kalkanı olarak kullanır', 1, 0, 0, 1, 0)),
    Q('kisilik', 'Onu en iyi tanımlayan kelime?',
      O('Sadık', 'onu en iyi tanımlayan kelime sadakattir; dostuna ölene dek arka çıkar', 0, 3, 1, 0, 0),
      O('Hırslı', 'onu en iyi hırs tanımlar; durmak, doymak bilmez', 2, 0, 2, 1, 1),
      O('Tehlikeli', 'onu en iyi tehlikeli kelimesi anlatır; sakin görünür ama içinde fırtına taşır', 3, -1, 1, 1, 2),
      O('Zeki', 'onu en iyi zekâsı tanımlar; herkesten bir hamle öndedir', 0, 0, 1, 3, 0)),

    // ───────────────────────── GELECEK HEDEFLERİ (12) ─────────────────────────
    Q('gelecek', 'En büyük hayali nedir?',
      O('Şehrin kralı olmak', 'en büyük hayali şehrin kralı olmaktır; her köşede sözünün geçtiği bir imparatorluk kurmak ister', 2, -1, 3, 0, 1),
      O('Geçmişini geride bırakmak', 'tek hayali geçmişini geride bırakıp temiz bir sayfa açmaktır', 0, 1, 0, 1, 0),
      O('Ailesine güvenli bir hayat', 'tüm çabası ailesine güvenli bir hayat kurmak içindir; gerisi teferruattır', 0, 2, 1, 0, 0),
      O('Ölümsüz bir isim bırakmak', 'öldükten sonra bile konuşulacak bir isim bırakmak ister; unutulmak en büyük korkusudur', 1, 0, 2, 1, 1)),
    Q('gelecek', 'Neye ulaşmak istiyor?',
      O('Mutlak güce', 'mutlak güce ulaşmak ister; kimsenin ona emir veremeyeceği bir konuma', 2, -1, 3, 1, 1),
      O('Huzura ve sükûnete', 'huzura ulaşmak ister; gürültülü hayatının ardından sessiz bir liman arar', 0, 1, 0, 0, -1),
      O('Adalete (kendi adaletine)', 'kendi adaletini kurmak ister; sistemin veremediğini kendi eliyle vermeye kararlıdır', 2, 0, 2, 1, 1),
      O('Servete ve konfora', 'servete ve konfora ulaşmak ister; çektiği yoklukların acısını çıkaracaktır', 1, 0, 1, 1, 0)),
    Q('gelecek', 'On yıl sonra kendini nerede görüyor?',
      O('Bir imparatorluğun tepesinde', 'on yıl sonra kendini bir imparatorluğun tepesinde görür; aşağıdakiler hep yukarı bakacak', 2, -1, 3, 1, 1),
      O('Sahilde, emekli ve huzurlu', 'on yıl sonra sahilde, tüm kavgaları geride bırakmış, huzurlu biri olmak ister', 0, 1, 0, 0, -1),
      O('Hâlâ ayakta, hâlâ savaşırken', 'on yıl sonra da ayakta, hâlâ savaşıyor olacağını bilir; durmak ölmektir ona göre', 1, 0, 1, 0, 1),
      O('Bilinmeyen bir yerde, yeni bir kimlikle', 'on yıl sonra kimsenin bulamayacağı bir yerde, yeni bir isimle yaşıyor olmak ister', 1, -1, 0, 1, 1)),
    Q('gelecek', 'Bir şeyi geri alabilseydi ne olurdu?',
      O('Kaybettiği birini', 'bir şeyi geri alabilse, kaybettiği o kişiyi geri getirirdi; gerisi bir hiçti', 0, 1, 0, 0, 0),
      O('Verdiği yanlış bir kararı', 'bir şeyi geri alabilse, hayatını değiştiren o yanlış kararı düzeltirdi', 0, 1, 1, 1, 0),
      O('Hiçbir şeyi, her şeye razı', 'hiçbir şeyi geri almazdı; bugünkü hâlini o yolların yarattığını bilir', 1, 0, 1, 1, 1),
      O('Masumiyetini', 'bir şeyi geri alabilse, çoktan yitirdiği masumiyetini geri isterdi', 1, 0, 0, 0, 1)),

    // ═══════════ EK HAVUZ — tekrarı azaltmak için ═══════════
    // ── Çocukluk (ek 8) ──
    Q('cocukluk', 'Çocukken evde en çok ne konuşulurdu?',
      O('Para sıkıntısı', 'evde hep para sıkıntısı konuşulurdu; küçük yaşta hesap kitap öğrendi', 1, 0, 0, 1, 0),
      O('Mahalle dedikoduları', 'evde sürekli mahalle konuşulurdu; kimin neyi gizlediğini dinleyerek büyüdü', 0, 0, 0, 2, 0),
      O('Borçlar ve alacaklar', 'evde borç-alacak eksik olmazdı; verilen sözün ağırlığını erken kavradı', 1, 0, 1, 1, 0),
      O('Hiçbir şey, sessiz bir evdi', 'evde konuşmak yerine susmak adettendi; iç dünyasına erken çekildi', 0, 0, 0, 1, 0)),
    Q('cocukluk', 'Çocukken nasıl bir öğrenciydi denince akla ne gelir?',
      O('Soru soran meraklı çocuk', 'durmadan soru soran meraklı bir çocuktu; öğrenme açlığı hiç dinmedi', 0, 1, 1, 2, 0),
      O('Arka sırada hayal kuran', 'arka sırada oturup hayal kuran biriydi; aklı hep başka diyarlardaydı', 0, 0, 0, 1, 1),
      O('Herkesi güldüren afacan', 'sınıfın afacanıydı; insanları güldürmeyi ve etrafında toplamayı severdi', 0, 0, 2, 0, 1),
      O('Öğretmenle inatlaşan dik kafalı', 'otoriteyle inatlaşan dik kafalı bir çocuktu; boyun eğmek ona göre değildi', 1, -1, 1, 0, 2)),
    Q('cocukluk', 'İlk büyük kavgasını ne için yaptı?',
      O('Kardeşini korumak için', 'ilk kavgasını kardeşini korumak için yaptı; aile için yumruk atmayı küçükken öğrendi', 1, 1, 1, 0, 1),
      O('Onurunu korumak için', 'ilk kavgası onuru içindi; itibarına dokunana boyun eğmedi', 1, 0, 1, 0, 1),
      O('Bir haksızlığa karşı', 'ilk kavgasını bir haksızlığa dur demek için verdi; adalet duygusu o yaşta belliydi', 1, 1, 1, 0, 1),
      O('Sebepsiz, sırf öfkeden', 'ilk kavgası sebepsizdi; içindeki öfkeyi yumruklarıyla boşalttı', 2, -1, 0, 0, 2)),
    Q('cocukluk', 'Çocukken hangi oyunu oynardı?',
      O('Lider seçildiği takım oyunları', 'oyunlarda hep kaptan seçilirdi; küçükken bile peşinden gidilen biriydi', 0, 1, 2, 0, 0),
      O('Tek başına zekâ oyunları', 'tek başına zekâ oyunları oynardı; kafasını çalıştırmak en büyük keyfiydi', 0, 0, 0, 2, 0),
      O('Tehlikeli sokak oyunları', 'tehlikeli sokak oyunlarını severdi; korkusuzluğu o zamandan belliydi', 1, 0, 1, 0, 2),
      O('Hile yaptığı oyunlar', 'oyunlarda hile yapmayı bir hüner sayardı; kazanmak için yolunu bulurdu', 1, -1, 0, 2, 1)),
    Q('cocukluk', 'Çocukken en değerli eşyası neydi?',
      O('Babasından kalan bir hatıra', 'en değerli eşyası babasından kalan bir hatıraydı; köklerine sıkı sıkı bağlandı', 0, 1, 0, 0, 0),
      O('Eski bir bıçak', 'en değerli eşyası eski bir bıçaktı; küçükken bile kendini korumayı düşünürdü', 2, -1, 0, 0, 1),
      O('Biriktirdiği bozuk paralar', 'kavanozda biriktirdiği bozuk paralardı en kıymetlisi; tasarrufu küçükken öğrendi', 0, 1, 0, 1, 0),
      O('Bir defter dolusu plan', 'bir defter dolusu çizim ve plandı en değerlisi; hayalleri hep kâğıttaydı', 0, 0, 1, 2, 0)),
    Q('cocukluk', 'Çocukken otorite karşısında nasıldı?',
      O('Saygılı ve uyumlu', 'otoriteye saygılı ve uyumluydu; kuralların bir nedeni olduğuna inanırdı', -1, 1, 0, 1, -1),
      O('Sürekli sınırları zorlayan', 'otoritenin sınırlarını sürekli zorlardı; ne kadar ileri gidebileceğini merak ederdi', 1, -1, 1, 1, 2),
      O('Korkup geri çekilen', 'otorite karşısında korkup geri çekilirdi; sesini sonradan buldu', 0, 0, -1, 1, 0),
      O('Sessizce karşı çıkan', 'açıkça değil ama sessizce karşı çıkardı; isyanı içinde büyüdü', 1, 0, 1, 1, 1)),
    Q('cocukluk', 'Çocukluğunun kahramanı kimdi?',
      O('Annesi', 'kahramanı annesiydi; fedakârlığın ne demek olduğunu ondan gördü', 0, 2, 1, 0, 0),
      O('Bir çizgi roman karakteri', 'kahramanı bir çizgi roman kahramanıydı; adalet ve güç hayalini ondan kurdu', 0, 1, 1, 1, 0),
      O('Mahalleden bir kabadayı', 'kahramanı mahallenin kabadayısıydı; saygının korkuyla geldiğini sandı', 2, -1, 1, 0, 1),
      O('Hiç kimse', 'kahramanı yoktu; kendi kendinin kahramanı olmaya karar verdi', 1, 0, 2, 1, 0)),
    Q('cocukluk', 'Çocukken hangi söz kulağına kazındı?',
      O('"Güçlü ol, kimseye muhtaç olma"', '"güçlü ol, kimseye muhtaç olma" sözü kulağına küpe oldu; bağımsızlığa taptı', 1, 0, 2, 0, 0),
      O('"Dürüstlük her kapıyı açar"', '"dürüstlük her kapıyı açar" sözüne inandı; bu ilkeyi ömrü boyunca taşıdı', -1, 2, 0, 0, 0),
      O('"Kimseye güvenme"', '"kimseye güvenme" öğüdü iliklerine işledi; herkese mesafeli büyüdü', 1, -1, 1, 1, 0),
      O('"Korkak ölmeden önce bin kez ölür"', '"korkak bin kez ölür" sözüyle büyüdü; korkmamayı bir yaşam ilkesi yaptı', 1, 0, 1, 0, 2)),

    // ── Gençlik (ek 8) ──
    Q('genclik', 'Gençken nasıl giyinir, nasıl görünürdü?',
      O('Sade ama temiz, dikkat çekmeden', 'sade giyinir, dikkat çekmeden dolaşırdı; görünmezlik onun kalkanıydı', 0, 1, 0, 1, 0),
      O('Gösterişli, herkesin baktığı', 'gösterişe düşkündü; her girdiği yerde gözler ona dönsün isterdi', 1, 0, 2, 0, 1),
      O('Sert ve tehditkâr', 'sert bir görünüşü vardı; daha konuşmadan karşısındakine mesaj verirdi', 2, -1, 1, 0, 1),
      O('Umursamaz ve dağınık', 'kılığına hiç aldırmazdı; dış görünüş onun için zaman kaybıydı', 0, 0, 0, 1, 1)),
    Q('genclik', 'Gençken ilk büyük riski neydi?',
      O('Her şeyini bir işe yatırmak', 'gençken her şeyini tek bir işe yatırdı; ya hep ya hiç dedi', 1, 0, 1, 1, 2),
      O('Güçlü birine kafa tutmak', 'gençken güçlü birine kafa tuttu; bu cesaret ona hem düşman hem itibar kazandırdı', 2, 0, 2, 0, 2),
      O('Bilmediği bir şehre göçmek', 'gençken her şeyi bırakıp yabancı bir şehre göçtü; sıfırdan başlamaktan korkmadı', 0, 0, 1, 1, 1),
      O('Tehlikeli bir sırrı saklamak', 'gençken tehlikeli bir sırrın altına girdi; o yük onu yıllarca takip etti', 2, 0, 0, 1, 1)),
    Q('genclik', 'Gençken kimlerle takılırdı?',
      O('Sokağın kurtlarıyla', 'sokağın kurtlarıyla takılırdı; hayatta kalmanın kurallarını onlardan öğrendi', 2, -1, 1, 1, 1),
      O('Hırslı ve hayalperestlerle', 'hayalperest ama hırslı bir çevresi vardı; birlikte büyük düşlerdi', 1, 0, 2, 1, 0),
      O('Kitap kurtları ve kafa dengiyle', 'kafa dengi, okuyan bir çevreyle takılırdı; sohbetleri hep zihin açıcıydı', 0, 1, 1, 3, 0),
      O('Pek kimseyle, yalnızdı', 'pek kimseyle takılmazdı; yalnızlığı bir zayıflık değil tercih sayardı', 0, 0, 0, 1, 0)),
    Q('genclik', 'Gençliğinde ne için savaştı?',
      O('Bir yer edinmek için', 'gençliğini bir yer edinmek için harcadı; görünmez olmaktan bıkmıştı', 1, 0, 2, 1, 1),
      O('Ailesine bakmak için', 'gençken omzunda ailesinin yükü vardı; onlar için durmadan çalıştı', 0, 2, 1, 0, 0),
      O('Bir hayal için', 'bir hayal uğruna savaştı; herkes gülse de inadından dönmedi', 0, 1, 1, 1, 0),
      O('Hayatta kalmak için', 'gençliği yalnızca hayatta kalma savaşıydı; lüks değil nefes peşindeydi', 1, 0, 1, 1, 1)),
    Q('genclik', 'Gençken otoriteyle (polis/devlet) ilişkisi?',
      O('Mesafeli ama sorunsuz', 'otoriteyle arası mesafeli ama sorunsuzdu; gözüne batmamayı bilirdi', 0, 1, 0, 1, 0),
      O('Sürekli sürtüşme hâlinde', 'otoriteyle sürekli sürtüştü; sabıka değil ama şöhret biriktirdi', 2, -1, 1, 0, 2),
      O('Kovalamaca ve kaçış', 'gençliği kovalamaca ve kaçışla geçti; tedbiri ve hızı orada öğrendi', 2, -1, 1, 1, 1),
      O('İçeriden bir tanıdıkla yürüten', 'otoritenin içinden bir tanıdıkla işini yürütürdü; bağlantının gücünü erken keşfetti', 2, -1, 1, 2, 0)),
    Q('genclik', 'Gençken en çok neyin peşindeydi?',
      O('Saygı', 'gençken saygının peşindeydi; adının anılır olması her şeyden önemliydi', 1, 0, 2, 0, 1),
      O('Para', 'gençken tek derdi paraydı; cebi dolunca dünyanın değiştiğini gördü', 1, 0, 1, 1, 0),
      O('Heyecan', 'gençken heyecanın peşindeydi; durağanlık onu boğardı', 1, -1, 0, 0, 2),
      O('Bilgi ve bağlantı', 'gençken bilgi ve bağlantı biriktirdi; asıl gücün burada olduğunu sezdi', 1, 0, 1, 3, 0)),
    Q('genclik', 'Gençken bir lidere mi uydu, kendi mi liderlik etti?',
      O('Güçlü bir lidere biat etti', 'gençken güçlü bir lidere biat etti; önce takip etmeyi, sonra yönetmeyi öğrendi', 1, 1, 0, 1, 0),
      O('Kendi küçük ekibini kurdu', 'gençken kendi ekibini kurdu; daha o yaşta etrafında bir halka oluştu', 1, 0, 3, 1, 1),
      O('Ne uydu ne liderlik etti, tek takıldı', 'ne birine uydu ne de liderlik etti; kendi başının çaresine baktı', 1, 0, 0, 1, 1),
      O('Liderle çatışıp yerine geçti', 'uyduğu liderle çatıştı ve yerine geçti; ihtirası sadakatini yendi', 3, -2, 2, 1, 2)),
    Q('genclik', 'Gençliğinin sonunda neye karar verdi?',
      O('Artık kuralları kendi koyacağına', 'gençliğinin sonunda artık kuralları kendisinin koyacağına karar verdi', 2, -1, 2, 1, 1),
      O('Temiz bir hayat kuracağına', 'gençliğinin sonunda temiz bir hayat kurmaya yemin etti; geçmişe sırtını döndü', -1, 2, 0, 1, -1),
      O('Kimseye güvenmeyeceğine', 'gençliğinin sonunda bir daha kimseye güvenmemeye karar verdi', 1, -1, 1, 1, 0),
      O('Ne olursa olsun zirveye çıkacağına', 'gençliğinin sonunda zirveye çıkmaya ant içti; bedeli neyse ödemeye razıydı', 2, 0, 2, 1, 1)),

    // ── Kırılma Noktaları (ek 9) ──
    Q('donum', 'Onu bugünkü hâline getiren tek olay?',
      O('Bir gece tek bir karar', 'bir gece verdiği tek bir karar tüm hayatını değiştirdi; o eşiği bir daha geçemedi', 2, 0, 1, 1, 1),
      O('Yılların sessiz birikimi', 'tek bir olay değil, yılların sessiz birikimi onu bugünkü hâline getirdi', 0, 1, 1, 1, 0),
      O('Bir kişinin hayatına girmesi', 'bir kişinin hayatına girmesi her şeyi değiştirdi; ondan önce ve sonra diye ikiye ayrıldı', 0, 1, 0, 0, 0),
      O('Dibe vurup yeniden doğması', 'en dibe vurduğu an yeniden doğdu; küllerinden bambaşka biri çıktı', 1, 0, 2, 1, 1)),
    Q('donum', 'Hayatında bir kez ağladıysa nedeni neydi?',
      O('Birini kaybetmek', 'bir kez ağladıysa sevdiğini kaybettiği içindi; o gözyaşı onu yumuşatmadı, sertleştirdi', 1, 0, 1, 0, 1),
      O('Çaresizlik', 'bir kez ağladıysa çaresizliktendi; o günden sonra asla çaresiz kalmamaya yemin etti', 1, 0, 1, 1, 0),
      O('İhanet', 'bir kez ağladıysa ihanettendi; o yaş kuruyunca kalbi de taşlaştı', 1, -1, 1, 1, 1),
      O('Hiç ağlamadı', 'kimse onu ağlarken görmedi; gözyaşını bir zayıflık sayıp içine gömdü', 1, -1, 1, 0, 1)),
    Q('donum', 'Bir sınırı ilk kez ne zaman aştı?',
      O('Birini korumak zorunda kaldığında', 'ilk sınırı sevdiğini korurken aştı; o an kendinde bilmediği bir yön keşfetti', 2, 1, 1, 0, 1),
      O('Sıkışıp başka çaresi kalmadığında', 'köşeye sıkışınca ilk kez bir sınırı aştı; mecburiyet ona yeni bir yüz taktı', 2, 0, 1, 1, 1),
      O('Hırsı gözünü bürüdüğünde', 'hırsı gözünü bürüdüğünde ilk sınırı aştı; o tat damağında kaldı', 3, -2, 1, 1, 2),
      O('Henüz hiçbir sınırı aşmadı', 'henüz aşmadığı sınırlar onun son kalesi; o çizgiyi korumak ona bir gurur', -1, 2, 0, 1, -1)),
    Q('donum', 'Geçmişiyle nasıl bir ilişkisi var?',
      O('Geçmişiyle barışık', 'geçmişiyle barışıktır; yaptığı her şeyi bugünkü gücünün temeli sayar', 0, 1, 1, 1, 0),
      O('Geçmişinden kaçıyor', 'geçmişinden kaçar; eski adını duymak bile içini ürpertir', 1, 0, 0, 1, 1),
      O('Geçmişinin esiri', 'geçmişinin esiridir; eski hesaplar yakasını bir türlü bırakmaz', 1, -1, 0, 0, 1),
      O('Geçmişini silah gibi kullanır', 'geçmişini bir silah gibi kullanır; başından geçenler ona heybet katar', 2, -1, 1, 1, 1)),
    Q('donum', 'Birine son bir şans verir mi?',
      O('Evet, herkes hata yapar der', 'son bir şans vermekten çekinmez; herkesin bir kez yanılabileceğine inanır', 0, 2, 0, 0, 0),
      O('Hayır, bir kez kıran bin kez kırar', 'son şans diye bir şeye inanmaz; bir kez ihanet eden gözünden ebediyen düşer', 1, -1, 1, 1, 0),
      O('Duruma ve kişiye göre', 'son şansı duruma göre verir; herkese değil, hak edene', 0, 1, 1, 2, 0),
      O('Verir ama asla unutmaz', 'son şansı verir ama defterden silmez; affeder gibi yapıp her şeyi hatırlar', 1, 0, 1, 2, 0)),
    Q('donum', 'En çok neyi kanıtlamaya çalışıyor?',
      O('Güçlü olduğunu', 'sürekli güçlü olduğunu kanıtlamaya çalışır; zayıf görünmek en büyük korkusu', 2, -1, 2, 0, 1),
      O('Yanıldıklarını', 'kendisini küçümseyenlerin yanıldığını kanıtlamaya çalışır; bu öfke onu besler', 1, 0, 2, 1, 1),
      O('Değiştiğini', 'değiştiğini kanıtlamaya çalışır; geçmişinin onu tanımlamasına izin vermez', 0, 1, 0, 1, 0),
      O('Hiçbir şey, kimseye bir şey borçlu değil', 'kimseye bir şey kanıtlama derdi yoktur; ne düşünüldüğü umurunda değildir', 1, 0, 1, 1, 1)),
    Q('donum', 'Hayatındaki dönüm noktasında yanında kim vardı?',
      O('Tek başınaydı', 'en kritik dönemecinde yapayalnızdı; kimsesizliği onu çelikleştirdi', 1, 0, 1, 1, 1),
      O('Sadık bir dostu', 'dönüm noktasında sadık bir dostu yanındaydı; o destek belki de her şeyi değiştirdi', 0, 2, 1, 0, 0),
      O('Bir akıl hocası', 'dönemeçte bir akıl hocası ona yol gösterdi; o öğütler hâlâ kulağında', 0, 1, 1, 2, 0),
      O('Onu kullanmak isteyen biri', 'dönemeçte yanındaki kişi onu kullanmak istedi; bu ders güven anlayışını kökten değiştirdi', 1, -1, 1, 2, 1)),
    Q('donum', 'O olaydan sonra neye inanmayı bıraktı?',
      O('İyi insanların kazandığına', 'o günden sonra iyilerin kazandığına inanmayı bıraktı; oyunu kendi kurallarıyla oynamaya başladı', 2, -1, 1, 1, 1),
      O('Sisteme ve adalete', 'o günden sonra sisteme inancını yitirdi; adaleti kendi eline aldı', 2, 0, 1, 1, 1),
      O('Aşka ve sadakate', 'o günden sonra sadakate inanmaz oldu; kalbini sıkı sıkı kilitledi', 1, -1, 1, 1, 0),
      O('Hiçbir şeye, inancını korudu', 'her şeye rağmen inancını korudu; karanlığın ortasında bile umudu söndürmedi', -1, 2, 1, 0, -1)),
    Q('donum', 'Onu durdurabilecek tek şey nedir?',
      O('Sevdiği biri', 'onu durdurabilecek tek şey sevdiği birinin sözüdür; gerisi onu yolundan çeviremez', 0, 1, 1, 0, 0),
      O('Kendi vicdanı', 'onu ancak kendi vicdanı durdurabilir; dış hiçbir güç onu eğemez', 0, 2, 1, 1, 0),
      O('Hiçbir şey', 'onu hiçbir şey durduramaz; bir kez kafasına koydu mu sonuna kadar gider', 2, -1, 2, 0, 2),
      O('Ölüm, başka bir şey değil', 'onu yalnızca ölüm durdurabilir derler; bu inat hem gücü hem laneti', 2, 0, 2, 0, 2)),

    // ── Kariyer (ek 8) ──
    Q('kariyer', 'İş ortağı seçerken neye bakar?',
      O('Sadakatine', 'iş ortağında önce sadakate bakar; yetenek sonra gelir', 1, 2, 1, 0, 0),
      O('Yeteneğine', 'iş ortağında yeteneği önemser; işi bilen biri her şeye değer', 1, 0, 1, 2, 0),
      O('Kullanışlılığına', 'iş ortağını kullanışlılığına göre seçer; işi bitince yollar ayrılabilir', 2, -2, 1, 2, 1),
      O('Cesaretine', 'iş ortağında cesaret arar; korkak biri en kötü anda dağılır', 2, 0, 1, 0, 1)),
    Q('kariyer', 'Kendi ekibini nasıl yönetir?',
      O('Adil paylaşım ve saygıyla', 'ekibini adil paylaşım ve saygıyla yönetir; herkes hakkını alır', 0, 2, 2, 1, 0),
      O('Sıkı disiplin ve korkuyla', 'ekibini sıkı disiplinle yönetir; gevşekliğe yer yoktur', 3, -1, 2, 0, 1),
      O('Herkese ayrı strateji ile', 'ekibinde herkese ayrı bir dille konuşur; kimi över, kimi sıkıştırır', 1, 0, 2, 3, 0),
      O('Gevşek, herkes kendi başına', 'ekibini gevşek tutar; herkes kendi işine bakar, o sadece yön verir', 1, 0, 0, 1, 1)),
    Q('kariyer', 'En büyük iş başarısı ne oldu?',
      O('Sıfırdan bir düzen kurmak', 'en büyük başarısı sıfırdan kendi düzenini kurmaktı; yoktan var etti', 1, 1, 2, 1, 0),
      O('Güçlü bir rakibi alt etmek', 'en büyük başarısı güçlü bir rakibi alt etmekti; o zafer adını duyurdu', 2, 0, 2, 1, 1),
      O('Herkesin güvendiği isim olmak', 'en büyük başarısı herkesin güvendiği isim olmaktı; itibarını paraya tercih etti', 0, 3, 1, 1, 0),
      O('Bir imparatorluğu ele geçirmek', 'en büyük başarısı hazır bir imparatorluğu ele geçirmekti; akıllıca oynayıp tahta oturdu', 2, -1, 2, 2, 1)),
    Q('kariyer', 'Bir işi alırken en çok neyi düşünür?',
      O('Riskini', 'bir işe girmeden önce riskini ölçer; gözü kapalı adım atmaz', 0, 1, 1, 2, 0),
      O('Kârını', 'bir işte önce kârı görür; rakamlar tutmuyorsa masaya oturmaz', 1, 0, 1, 2, 0),
      O('Kimlerin karışacağını', 'bir işte kimlerin olduğuna bakar; yanlış isimlerle aynı masaya oturmaz', 1, 0, 1, 2, 0),
      O('Heyecanını', 'bir işte önce heyecanı arar; sıkıcıysa kâr bile onu çekmez', 1, -1, 0, 0, 2)),
    Q('kariyer', 'Rakipleri onun için ne der?',
      O('"Sözünün eridir ama tehlikelidir"', 'rakipleri onu "sözünün eri ama tehlikeli" diye anar; saygı ve korku bir arada', 1, 1, 2, 1, 1),
      O('"Asla güvenme, her an döner"', 'rakipleri "ona asla güvenme" der; ne zaman taraf değiştireceği bilinmez', 2, -2, 1, 2, 1),
      O('"Akıllıdır, hep bir adım önde"', 'rakipleri onun zekâsından çekinir; "hep bir adım önde" derler', 1, 0, 1, 3, 0),
      O('"Delidir, gözü hiçbir şey görmez"', 'rakipleri onu "deli" diye anar; gözünü karartınca durdurulamaz', 3, -1, 1, 0, 3)),
    Q('kariyer', 'Para ve itibar arasında seçim yapsa?',
      O('İtibarı seçer', 'para ile itibar arasında itibarı seçer; adı temiz kalsın ister', 0, 2, 2, 1, 0),
      O('Parayı seçer', 'para ile itibar arasında parayı seçer; cüzdan dolunca gerisi gelir der', 1, -1, 1, 1, 0),
      O('İkisini birden ister, ödün vermez', 'ne paradan ne itibardan ödün verir; ikisini birden ister', 1, 0, 2, 1, 1),
      O('Duruma göre değişir', 'kimi zaman parayı kimi zaman itibarı seçer; pragmatiktir, duruma bakar', 1, 0, 1, 2, 1)),
    Q('kariyer', 'Yasayla arası nasıl?',
      O('Yasalara saygılı', 'yasalara saygılıdır; çizginin dışına çıkmamaya özen gösterir', -2, 2, 0, 1, -1),
      O('Yasayı esnetir ama kırmaz', 'yasayı esnetir ama bütünüyle kırmaz; gri alanın ustasıdır', 1, 0, 1, 2, 1),
      O('Yasayı umursamaz', 'yasayı pek umursamaz; kendi kuralları onun için daha bağlayıcıdır', 3, -2, 1, 0, 2),
      O('Yasayı kendi lehine kullanır', 'yasayı kendi lehine kullanmayı bilir; boşluklardan sıyrılmakta ustadır', 2, -1, 1, 3, 0)),
    Q('kariyer', 'Bir krizde ilk hamlesi ne olur?',
      O('Ekibini toplayıp plan yapmak', 'krizde önce ekibini toplar, soğukkanlı bir plan yapar', 0, 1, 2, 2, 0),
      O('Tehdidi anında bastırmak', 'krizde tehdidi anında ve sert biçimde bastırır; tereddüt etmez', 3, -1, 2, 0, 1),
      O('Sessizce geri çekilip beklemek', 'krizde sessizce geri çekilir, fırtınanın geçmesini bekler', 0, 0, 0, 2, 0),
      O('Kaosu fırsata çevirmek', 'krizde herkes kaybederken o kazanır; kaosu fırsata çevirir', 1, -1, 1, 3, 1)),

    // ── Sosyal Hayat (ek 8) ──
    Q('sosyal', 'Bir toplulukta nasıl bir roldedir?',
      O('Herkesin güvendiği abi/abla', 'bir toplulukta herkesin güvendiği abi figürüdür; sorunlar ona getirilir', 0, 2, 2, 1, 0),
      O('Sessiz ama sözü dinlenen', 'sessizdir ama konuştuğunda herkes susar; az ve öz konuşur', 0, 1, 2, 2, 0),
      O('Ortalığı karıştıran kıvılcım', 'bir toplulukta kıvılcımdır; durgun suyu o dalgalandırır', 1, -1, 1, 1, 2),
      O('Kenarda gözlemleyen', 'kalabalığın kenarında durur, herkesi gözlemler; bilgisini sessizce toplar', 1, 0, 0, 2, 0)),
    Q('sosyal', 'Düşmanlarına karşı tavrı nedir?',
      O('Açıkça karşılarına dikilir', 'düşmanının karşısına açıkça dikilir; arkadan iş çevirmeyi sevmez', 1, 1, 2, 0, 1),
      O('Sessizce bekler, fırsat kollar', 'düşmanına karşı sabreder; doğru anı kollar, sonra vurur', 2, -1, 1, 3, 1),
      O('Önce dost olmayı dener', 'düşmanını bile masaya çağırır; mümkünse kan dökmeden çözer', 0, 1, 1, 2, 0),
      O('Acımasızca ezer', 'düşmanını acımasızca ezer; örnek olsun, bir daha kimse denemesin ister', 3, -2, 2, 0, 2)),
    Q('sosyal', 'Güveni nasıl kazanılır?',
      O('Zamanla ve emekle', 'güveni zamanla ve emekle kazanılır; kestirme yol yoktur', 0, 2, 1, 1, 0),
      O('Bir kez sınanarak', 'güveni tek bir sınavla kazanılır; ateşten geçen içeri alınır', 1, 1, 1, 1, 0),
      O('Neredeyse imkânsızdır', 'güvenini kazanmak neredeyse imkânsızdır; herkese kapısı kapalıdır', 1, -1, 1, 1, 0),
      O('Çıkar birliğiyle', 'güveni ortak çıkarla kazanılır; menfaat sürdükçe güven sürer', 1, -1, 1, 2, 0)),
    Q('sosyal', 'Kalabalık mı yalnızlık mı?',
      O('Kalabalığın enerjisini sever', 'kalabalığın enerjisini sever; insanların arasında hayat bulur', 0, 1, 2, 0, 1),
      O('Yalnızlığı tercih eder', 'yalnızlığı tercih eder; kalabalık onu yorar, sessizlik dinlendirir', 0, 0, 0, 2, 0),
      O('Az ama gerçek dostları yeter', 'az ama gerçek birkaç dost ona yeter; kalabalığa ihtiyacı yoktur', 0, 2, 1, 1, 0),
      O('Kalabalığı kullanır, yalnız hisseder', 'kalabalığın içinde olur ama hep yalnız hisseder; insanları bir araç gibi görür', 1, -1, 1, 1, 1)),
    Q('sosyal', 'Birine "kardeşim" dediğinde ne anlama gelir?',
      O('Ölümüne sadakat', '"kardeşim" dediği kişi için ölümüne sadıktır; o söz bir yemin gibidir', 1, 3, 1, 0, 1),
      O('Şimdilik güvendiği biri', '"kardeşim" sözü ondan şimdilik güvendiği biri demektir; şartlar değişebilir', 1, -1, 1, 1, 0),
      O('Bir alışkanlık, herkese der', '"kardeşim" sözü onda bir alışkanlıktır; herkese der, derinliği değişir', 0, 0, 1, 0, 1),
      O('Stratejik bir yakınlık', '"kardeşim" dediği kişiyle stratejik bir bağ kurar; her yakınlığın bir amacı vardır', 1, -1, 1, 2, 0)),
    Q('sosyal', 'Bir sır verilse ne yapar?',
      O('Mezara kadar saklar', 'verilen sırrı mezara kadar saklar; ağzı sıkılığı meşhurdur', 0, 3, 1, 1, 0),
      O('Gerekirse koz olarak kullanır', 'sırrı saklar ama gerekirse bir koz olarak masaya sürer', 2, -2, 1, 2, 0),
      O('Yanlışlıkla ağzından kaçırır', 'sır tutmakta zorlanır; bazen yanlışlıkla ağzından kaçırır', 0, -1, 0, -1, 1),
      O('En yakınıyla paylaşır', 'sırrı kimseye söylemez ama en yakınından da gizleyemez', 0, 0, 0, 1, 0)),

    // ── Karakter Özellikleri (ek 8) ──
    Q('kisilik', 'Tehlike karşısında refleksi nedir?',
      O('Soğukkanlı analiz', 'tehlikede soğukkanlı kalır, durumu hızla analiz eder; panik ona uğramaz', 1, 1, 2, 3, -1),
      O('Anında saldırı', 'tehlikede önce vurur sonra düşünür; refleksi hücumdur', 3, -1, 1, 0, 2),
      O('Hızlı kaçış planı', 'tehlikede en yakın çıkışı bulur; yaşamak gururdan önce gelir', 1, -1, 0, 2, 1),
      O('Blöf ve manipülasyon', 'tehlikede diliyle kurtulur; blöf ve ikna onun kalkanıdır', 2, -1, 1, 3, 1)),
    Q('kisilik', 'En sevdiği kazanma yolu?',
      O('Adil rekabetle', 'kazanmayı adil rekabetle sever; hileyle gelen zafer ona tat vermez', 0, 2, 1, 1, 0),
      O('Rakibi şaşırtarak', 'kazanmayı rakibini şaşırtarak sever; beklenmedik hamleler onun imzasıdır', 1, 0, 1, 3, 1),
      O('Ne olursa olsun, sonuç önemli', 'kazanmak için yol önemli değildir; sonuç ne ise gerisi teferruattır', 2, -2, 1, 1, 1),
      O('Karşısındakini ezerek', 'kazanmayı rakibini tamamen ezerek sever; yarım zafer ona göre değildir', 3, -1, 2, 0, 2)),
    Q('kisilik', 'İçindeki en güçlü ses hangisi?',
      O('Vicdanı', 'içindeki en güçlü ses vicdanıdır; yanlış yapınca uyuyamaz', 0, 2, 1, 1, -1),
      O('Hırsı', 'içindeki en güçlü ses hırsıdır; "daha fazla" diye fısıldar durur', 2, -1, 2, 1, 1),
      O('Korkuları', 'içindeki en güçlü ses korkularıdır; çoğu kararını o korkular şekillendirir', 1, 0, 0, 1, 1),
      O('Mantığı', 'içindeki en güçlü ses mantığıdır; duyguyu hep ikinci plana atar', 0, 1, 1, 3, -1)),
    Q('kisilik', 'Affetmek mi intikam mı?',
      O('Affetmeyi seçer', 'affetmeyi seçer; kin tutmanın insanı içten çürüttüğüne inanır', -1, 2, 1, 1, -1),
      O('İntikamı tercih eder', 'intikamı tercih eder; ödenmeyen hesabın kapanmayacağına inanır', 2, -1, 1, 1, 1),
      O('Affeder ama unutmaz', 'affeder ama asla unutmaz; bağışlaması bir daha güvendiği anlamına gelmez', 1, 0, 1, 2, 0),
      O('Duruma göre karar verir', 'kimi zaman affeder kimi zaman hesap sorar; tek bir kuralı yoktur', 1, 0, 1, 2, 1)),
    Q('kisilik', 'Güç eline geçtiğinde ne yapar?',
      O('Adaletle kullanır', 'güç eline geçtiğinde onu adaletle kullanır; zayıfı ezmeyi küçüklük sayar', 0, 2, 2, 1, 0),
      O('Korku salmak için kullanır', 'güç eline geçtiğinde korku salar; herkes yerini bilsin ister', 3, -2, 2, 0, 1),
      O('Daha fazlasını istemek için', 'eline geçen güç hırsını körükler; hep daha fazlasını ister', 2, -1, 2, 1, 1),
      O('İhtiyatla, belli etmeden', 'gücünü belli etmeden, ihtiyatla kullanır; gösteriş onu zayıf düşürür sanır', 1, 0, 1, 3, 0)),
    Q('kisilik', 'Zayıf birini görünce ne hisseder?',
      O('Korumak ister', 'zayıf birini görünce korumak ister; güçsüzün yanında durmayı erdem sayar', 0, 2, 2, 0, 0),
      O('Fırsat olarak görür', 'zayıf birini fırsat olarak görür; her açığı bir kazanç kapısı sayar', 2, -2, 1, 2, 1),
      O('Görmezden gelir', 'zayıf birini görmezden gelir; herkes kendi savaşını versin der', 1, -1, 0, 1, 0),
      O('Kendini hatırlar, yardım eder', 'zayıf birinde eski hâlini görür ve elini uzatır; geçmişini unutmaz', 0, 1, 1, 0, 0)),
    Q('kisilik', 'En büyük çelişkisi nedir?',
      O('Sert görünür ama içi yumuşak', 'sert bir kabuğu vardır ama içi yumuşaktır; bu çelişki en insani yanıdır', 1, 1, 1, 0, 1),
      O('Güven ister ama kimseye güvenmez', 'güvenilmek ister ama kendisi kimseye güvenmez; bu çelişkiyle yaşar', 1, -1, 1, 1, 1),
      O('Huzur ister ama kavgadan kaçamaz', 'huzur özler ama kavgadan kaçamaz; sükûnet ona hep uzak kalır', 1, 0, 1, 0, 2),
      O('Yalnızlığı sever ama yalnızlıktan korkar', 'yalnızlığı sever ama bir yandan yalnız kalmaktan korkar; bu ikilemde gidip gelir', 1, 0, 0, 1, 1)),
    Q('kisilik', 'Onu bir hayvana benzetsek hangisi olurdu?',
      O('Kurt — sadık ama vahşi', 'onu bir kurda benzetirlerdi; sürüsüne sadık ama yeri geldiğinde vahşi', 1, 1, 2, 1, 1),
      O('Tilki — kurnaz ve temkinli', 'onu bir tilkiye benzetirlerdi; kurnaz, temkinli ve hep bir planı olan', 1, 0, 1, 3, 0),
      O('Aslan — gururlu ve baskın', 'onu bir aslana benzetirlerdi; gururlu, baskın ve sürüsünün lideri', 1, 0, 3, 1, 1),
      O('Yılan — sessiz ve ölümcül', 'onu bir yılana benzetirlerdi; sessiz, soğuk ve fark edilmeden vuran', 3, -2, 1, 2, 1)),

    // ── Gelecek Hedefleri (ek 8) ──
    Q('gelecek', 'Ölümünden sonra nasıl hatırlanmak ister?',
      O('Sözünün eri biri olarak', 'ardından "sözünün eriydi" densin ister; itibarı en kalıcı mirasıdır', 0, 3, 1, 0, 0),
      O('Korkulan bir efsane olarak', 'ardından korkulan bir efsane olarak anılmak ister; adı hâlâ ürpertsin', 2, -1, 2, 0, 1),
      O('Sevdiklerini koruyan biri olarak', 'ardından "bizi korudu" densin ister; ailesi için yaşadı, onlar için anılsın', 0, 2, 1, 0, 0),
      O('Hiç umursamıyor', 'öldükten sonra nasıl anılacağı umurunda değildir; yaşarken yaşamaya bakar', 1, 0, 1, 1, 1)),
    Q('gelecek', 'En çok neyden vazgeçemez?',
      O('Onurundan', 'her şeyden vazgeçer ama onurundan asla; o gidince hiçbir şey kalmaz der', 1, 1, 2, 0, 1),
      O('Sevdiklerinden', 'her şeyden vazgeçer ama sevdiklerinden asla; onlar onun tek zaafı ve tek gücü', 1, 2, 1, 0, 1),
      O('Hırsından', 'hırsından vazgeçemez; durmak ona ölmek gibi gelir', 2, -1, 2, 1, 1),
      O('Özgürlüğünden', 'özgürlüğünden asla vazgeçmez; zincir, altından bile olsa zincirdir', 1, 0, 1, 1, 1)),
    Q('gelecek', 'Bir mucize olsa ne dilerdi?',
      O('Kaybettiğini geri', 'bir mucize olsa kaybettiğini geri isterdi; servet değil, o kişi', 0, 1, 0, 0, 0),
      O('Temiz bir başlangıç', 'bir mucize olsa lekesiz, temiz bir başlangıç isterdi', 0, 1, 0, 1, 0),
      O('Sınırsız güç', 'bir mucize olsa sınırsız güç isterdi; geri kalan her şey bunun yanında küçüktü', 2, -1, 3, 1, 1),
      O('Hiçbir şey, her şeyi kendi yapmak ister', 'mucizeye inanmaz; her şeyi kendi elleriyle kazanmak ister', 0, 1, 2, 1, 0)),
    Q('gelecek', 'Hayatının sonunda neyi başarmış olmak ister?',
      O('Sevenleriyle huzurlu bir son', 'hayatının sonunda sevdikleriyle huzur içinde olmak ister; servet değil sıcaklık arar', 0, 2, 0, 0, -1),
      O('Adının efsane olması', 'hayatının sonunda adının bir efsaneye dönüşmüş olmasını ister', 1, 0, 2, 1, 1),
      O('Hiç kimseye boyun eğmemiş olmak', 'hayatının sonunda kimseye boyun eğmemiş olmakla övünmek ister', 2, -1, 2, 0, 1),
      O('Geçmişinin hesabını kapatmış olmak', 'hayatının sonunda tüm eski hesapları kapatmış, defteri temizlemiş olmak ister', 1, 0, 1, 1, 1)),

    // ── Son ekleme (denge) ──
    Q('sosyal', 'Yeni biriyle tanışınca ilk ne yapar?',
      O('Onu dinler, tartar', 'yeni biriyle tanışınca önce dinler, sessizce tartar; aceleci yargı vermez', 0, 1, 1, 2, 0),
      O('Hızlıca güvenir, sıcak davranır', 'yeni biriyle hemen sıcak ilişki kurar; insanlara çabuk ısınır', 0, 1, 1, 0, 1),
      O('Zaafını arar', 'yeni tanıştığı kişinin zaafını arar; herkeste bir açık olduğunu bilir', 2, -2, 1, 2, 0),
      O('Mesafe koyar, güvenmez', 'yeni birine mesafe koyar; güven kazanılana dek kapısını aralamaz', 1, 0, 1, 1, 0)),
    Q('sosyal', 'Kalabalık bir mekâna girdiğinde?',
      O('Çıkışları ve tehditleri tarar', 'bir mekâna girince önce çıkışları ve riskleri tarar; tedbiri elden bırakmaz', 1, 0, 1, 3, 0),
      O('Tüm dikkati üstüne çeker', 'bir mekâna girince tüm gözler ona döner; varlığı hissedilir', 1, 0, 2, 0, 1),
      O('Tanıdık yüz arar', 'bir mekâna girince tanıdık bir yüz arar; yabancılık onu tedirgin eder', 0, 1, 0, 1, 0),
      O('Köşeye çekilir, izler', 'bir mekânda köşeye çekilip ortamı izler; gölgede kalmayı yeğler', 1, 0, 0, 2, 0)),
    Q('gelecek', 'Hayatını bir cümleyle özetlese ne derdi?',
      O('"Yokluktan geldim, zirveye tırmandım"', 'hayatını "yokluktan geldim, zirveye tırmandım" diye özetlerdi; yükselişiyle gurur duyar', 1, 0, 2, 1, 1),
      O('"Hep doğru olanı yapmaya çalıştım"', 'hayatını "hep doğruyu yapmaya çalıştım" diye özetlerdi; vicdanı pusulasıdır', 0, 2, 1, 1, 0),
      O('"Kimseye boyun eğmedim"', 'hayatını "kimseye boyun eğmedim" diye özetlerdi; bağımsızlığı her şeyin üstündedir', 2, -1, 2, 0, 1),
      O('"Hayatta kalmak için her şeyi yaptım"', 'hayatını "hayatta kalmak için her şeyi yaptım" diye özetlerdi; pişman değildir', 2, -1, 1, 1, 1)),
    Q('gelecek', 'Bir vârise ne öğüt bırakırdı?',
      O('"Sözünden asla dönme"', 'vârisine "sözünden asla dönme" derdi; itibarın paradan kıymetli olduğunu öğretirdi', 0, 3, 1, 0, 0),
      O('"Kimseye güvenme, gözünü açık tut"', 'vârisine "kimseye güvenme, gözünü açık tut" derdi; ihtiyatı miras bırakırdı', 1, -1, 1, 2, 0),
      O('"Güçlü ol ya da ez geçilirsin"', 'vârisine "güçlü ol, yoksa ezilirsin" derdi; acımasız bir dünya tarif ederdi', 2, -1, 2, 0, 1),
      O('"Geçmişin seni tanımlamasın"', 'vârisine "geçmişin seni tanımlamasın" derdi; değişimin mümkün olduğuna inanırdı', 0, 1, 1, 1, 0))
  ]
};

if (typeof module !== 'undefined' && module.exports) module.exports = { STORYGEN_SEED: STORYGEN_SEED };
